### ISSUE TITLE
/var/www permisions

### ISSUE THREAD

**Issue by ghost** [icecoder/ICEcoder#1000]
Buenas tardes.
I have followed the ICECoder web tutorial to set permissions to the /var/www directory, but it doesn't work.
I don't know what I can be doing wrong.
I have done the following on my server.

sudo usermod -a -G XXXX www-data
sudo chown -R www-data: www-data /var/www
sudo chmod 775 -R /var/www

I set as main directory in ICECoder /var/www, and it tells me that it does not have access

can you help me?

Thank you very much to all and greetings!

**Comment by mattpass** [comment]
Hi @binary-hub - couple of things to check...

You've put ICEcoder also into `/var/www/ICEcoder`?
Is your user for the site definitely `www-data` (check the user listed for files you have in `www-data` to see what they are and that they can be shown in the browser.

To clarify also - you simply don't have access to sign into ICEcoder - or you don't have access to save files?
