### ISSUE TITLE
Safari - Ui damaged.

### ISSUE THREAD

**Issue by skerbis** [icecoder/ICEcoder#1001]
ICEcoder 8.1
In Safari 15.1 it looks like this: 

<img width="1186" alt="Bildschirmfoto 2021-11-22 um 15 00 50" src="https://user-images.githubusercontent.com/791247/142874892-c8c3c6bd-5936-46fd-93cc-e4db591780c8.png">

cannot figure out why
Can't get or see the menu

**Comment by mattpass** [comment]
@skerbis after much headscratching I've narrowed it down to the updated database manager lib, Adminer, which it seems causes the page to distort.

If you comment out this in `lib/database-adminer-480-en.php` on line `14`:

`include "./database-adminer-480-en.php";`

...and then reload, ICEcoder isn't distorted and works fine. I'll continue to investigate why it's affecting the display of ICEcoder itself, but should get you by in the meantime?

**Comment by skerbis** [comment]
Thanks. 👍🏻 It seems replacing it with Adminer 4.8.1 helps preventing this issue

**Comment by mattpass** [comment]
Indeed. Something is causing the display to distort - will find out exactly what and resolve. In the meantime, this is a good fix 👍🏼

**Comment by skerbis** [comment]
I thought an update of the adminer would help. Unfortunately not. It worked for a short time. But after a while the error was back. (Perhaps a caching issue)

**Comment by mattpass** [comment]
Someone else reported this issue too, which seems to be resolved now in a fix I made at: https://github.com/icecoder/ICEcoder/commit/958e91a67f594474299a01be35830172e1eb12d5 - hope it's sorted for you now also.
