### ISSUE TITLE
Images missing for installed Plugins (Wrong folder?) 

### ISSUE THREAD

**Issue by skerbis** [icecoder/ICEcoder#1005]
After installation of Plugins the images for these are not installed
for example: images/pesticide/icon.png

Icecoder looks for ` images/pesticide/icon.png` but in images there is only one file  file-manager-icons.png no plugin folder

I think it should look for `plugins/pesticide/icon.png`

<img width="801" alt="Bildschirmfoto 2021-12-16 um 10 29 54" src="https://user-images.githubusercontent.com/791247/146345103-a25ad095-490c-4799-a753-8a422c983b90.png">

**Comment by mattpass** [comment]
Thanks @skerbis for reporting this and yes, was the wrong folder. Fixed in https://github.com/icecoder/ICEcoder/commit/d6124b08115939ac06f88ff90f96a2a11561175b

You should be able to uninstall the icons and reinstall them to have this issue fixed for yourself.

Thanks again.
