### ISSUE TITLE
Login with URL function

### ISSUE THREAD

**Issue by matranovakifanyuvo** [icecoder/ICEcoder#1024]
Hey,

I would like login without form, only URL, example:

https://mysite.com/icecoder/?login_pw=12345678

It is possible?

**Comment by mattpass** [comment]
Having a password in the URL seems like a not very secure method and so not something that's been implemented.

If you'd like to have no login, you can edit `data/config-global.php` after ICEcoder has booted up and replace `"loginRequired";b:1` with `"loginRequired";b:0` to turn off the need for login.
