### ISSUE TITLE
Collab editing

### ISSUE THREAD

**Issue by mattpass** [icecoder/ICEcoder#242]
Using firebase.com and look at firepad.io for examples where multiple users can work on a document at the same time.

**Comment by Elxafil** [comment]
Is it possible to still have this feature implemented?

**Comment by mattpass** [comment]
@Elxafil anything is possible, but this is a closed issue because of the tech complications mentioned above and plenty of other features taking higher priority. It's open source code tho, so anyone with time could implement this.
