### ISSUE TITLE
Multiple projects "root" settings with one ICEcoder installation

### ISSUE THREAD

**Issue by vicenteherrera** [icecoder/ICEcoder#246]
Maybe related to issues #216 y #162 

It would be nice having a sigle ICEcoder installation, but with different settings file, so each one can have a different "root".

Maybe that could be achieved asking user and password, and using for each user a different settings file.
## 

What I'm thinking is an environment where we have like twenty students, each one with his/her own project home, but all of them access the same ICEcoder folder. Right now this can be achieved making a different copy of ICEcoder to each user folder.

Also I'm think of a form for "initialisation of project", so first time user logs in, a folder is created using username, it is populated with the base project from the contents of a zip.

In my opinion, not having to use a real BD is nicer: user information for 20 students is not that much data to have in an php array of meta-settings.

It would be very useful for classes, coding dojos, etc. I think I'll ducktape something like this with ugly PHP, but here I put the idea so it can influence the main development of ICEcoder.

**Comment by firstygoldfish** [comment]
Hi Did workspaces ever make it into a release?

**Comment by mattpass** [comment]
Not as yet @firstygoldfish - always seems to be on the 'to do' list. Is currently due to be done in v5.3 (see https://github.com/mattpass/ICEcoder/issues/459). Got to get that done soon tho, is one of the most requested features.

**Comment by Aslamfarook** [comment]
Hi All,

I have configured ICE coder in azure vm.I can able to login in to via browser with credential but in my case i want to login with multiple user with different credential  while doing this i have copied the config file of old user and rename with name for example config-admin-ip.php  to config-aslam-ip.php.
after this change it is working 
But my question is we need to do this manually for every user?

**Comment by labKnowledge** [comment]
Hi all,

I am using this tool at our school but my fear is the way it expose all the data from the root folder of the website.

am running our server in linuxmint and the root folder is /var/www/html

how to show all students a certain level of folder? 

thanks

**Comment by mattpass** [comment]
@labKnowledge > how to show all students a certain level of folder?

You can go to the `Edit > Settings` option above the file manager and in the popup settings that show, add the relative path for `root` within the `General` tab. ie, if the path you want to show is `/var/www/html/sitedir` you would enter `/sitedir` as the setting.

Now when you hit the `Update` button, the top of the file manager is `/sitedir` and everything within.

**Please note tho** - ICEcoder is meant to be used by individual devs or teams of trusted people! It's fairly trivial for a student to undo this setting or tinker with things and get access to your root dir.
