### ISSUE TITLE
Text file encoding problems

### ISSUE THREAD

**Issue by vicenteherrera** [icecoder/ICEcoder#247]
There are some problems with the encoding of text files when you edit them from IDEcoder.
- If you encode your files with **ANSI** encoding, letters with accents (áéíóúÁÉÍÓÚñÑ) and similar characters (that are present in ANSI) doesn't show correctly, this is big problem here in Spain. This is the default encoding for files created from most Windows editors.
- If using **UTF-8** encoded files, the editor shows an extra character at the beginning of the file, (the "BOM" of the UTF standard). All special characters are shown correctly.
- If using **UTF-8 without BOM**, everything is shown correctly.
## 

Notes:

Maybe it's an issue of CodeMirror component directly. 

The more easy way to convert a text file to other encoding formats for testing in Windows is using Notepad++.

Different line ending formats (win/linux/mac) are treated correctly.

**Comment by katyamanecer** [comment]
Muy buen aporte estaba desesperada con un archivo y gracias a este post lo solucione
saluditos a todos
