### ISSUE TITLE
Click Save: Sorry, Cannot Write

### ISSUE THREAD

**Issue by ghost** [icecoder/ICEcoder#264]
Hi all,

Edit a file in Ice, click Save Icon
Get error message: Sorry, cannot write /var/www/index.html

Pretty sure it is just a permissions thing or run as user.

Apache2 on Ubuntu server 12.04

Suggestions?

Edit: Also getting error: Cannot Zip Files up.

**Comment by seyo-IV** [comment]
hi there  i have a similar problem. I cant save the files. Itriyed changing the read permission but it doesent help. I have the version 5 and im using a dcoker image.
I cant also update cuz i cant open the update.php and get http error 500. But this is another issue.
