### ISSUE TITLE
Better demo mode

### ISSUE THREAD

**Issue by nerodark** [icecoder/ICEcoder#341]
This is important feature for me:

Have a demo mode that does not ask for a user/password on start, go directly to edit mode (is it already like that?)
Also, allow file creation/editing in demo mode (create files, edit files, etc)

By that, i want to provide my users a little sandbox (in their own directory named by their session ids) where they can edit files anonymously

**Comment by brugnara** [comment]
@mattpass I know this is a little old but for me, with the 7.0 version, the `loginRequired` flag still requires me to create a password. Is this a wanted behavior?

Many thanks.

**Comment by mattpass** [comment]
Agreed - think it would be good to tweak so reopening and adding to 8.1's tasks.

**Comment by mattpass** [comment]
Have added this commit https://github.com/icecoder/ICEcoder/commit/4a08853605e813b8ee4bcb51dd239f3d3785f54b now which means if you have `loginRequired` set to `false`, you don't need to create a password.
