### ISSUE TITLE
20 languages in 20 days

### ISSUE THREAD

**Issue by mattpass** [icecoder/ICEcoder#375]
Right now, ICEcoder supports about 12 languages, which I've hand picked as the ones I think people will use most, on a Linux based setup.

Now and again tho, I get a request for a language and usually if I don't think it'll be popular enough, the response is that they can add it easily. This has been to avoid bloat in the main repo.

However, with a lot of code moved recently out into installable plugins, we're now very light on the main repo's filesize, so can probably fit in a few more languages.

So, below are the 20 languages I'm most asked for, which I'm now considering adding in:
- [x] C, C++, C#
- [ ] Clojure
- [ ] Common Lisp
- [x] Erlang
- [x] Go
- [x] Java
- [ ] HTTP
- [ ] Jade
- [x] Lua
- [ ] Pascal
- [ ] Pig Latin
- [ ] Properties files
- [ ] Puppet
- [x] Rust
- [x] Sass
- [ ] Shell
- [ ] Solr
- [ ] sTeX, LaTeX
- [ ] VB.net
- [x] YAML

These are all popular enough to consider including in the main repo, and won't add much to the overall size of ICEcoder.

So, what's the catch? You'll need to add something into the crowdfunding pot at http://igg.me/at/icecoder4

You're free to put in any amount you wish, but I'd say the smallest perk size there would be fine.

Let's see if we can get these built and almost triple the languages it supports!

**Comment by DJF3** [comment]
How can I add a language myself? (or where is a language defined?)
Or do you have an example of a plugin that adds a language definition?

**Comment by mattpass** [comment]
There's a short guide on how to add extra languages here: https://icecoder.net/manual#addingExtraLanguages The process is a little fiddly at the moment but should take around 10-15 mins. If you add a language you think others will like and it's relatively small to implement, a pull request would be great. :-)
