### ISSUE TITLE
Can not write despite the file has write permissions

### ISSUE THREAD

**Issue by martinb07** [icecoder/ICEcoder#444]
Hi
I set up icecoder for my new test site. On the first sight everysthing looks good, but when I want to save a file icecoder say, it can not write the file. 
I tried the thinks like changing the file owner of the icecoder files to the server and setting the edited file to chmod 777.

Please assist.Thank you.

cheers
marrtin

**Comment by DrakonAlpha** [comment]
Might the following path setting work?
> "docRoot"       => $_SERVER['DOCUMENT_ROOT/ICEcoder/project_folder']
