### ISSUE TITLE
Blocking Brute Force Attacks

### ISSUE THREAD

**Issue by AppoPro** [icecoder/ICEcoder#486]
How about to add [recaptcha](http://www.google.com/recaptcha/intro/) on login page ?

**Comment by mattpass** [comment]
Just too much going on for v5 launch. Moving this to v5.1.

**Comment by mattpass** [comment]
The login hashing algorithm is Bcrypt now as mentioned and has a cost of '10', the recommended baseline. This should help with brute force attempts but this kind of thing should not be covered in code really, instead in infrastructure.

Not going to add Recaptcha (as it's annoying and requires a call to an external service) and the same applies for 2FA really. If brute forcing is a concern, you're better off looking into services such as CloudFlare.
