### ISSUE TITLE
Bitbucket support

### ISSUE THREAD

**Issue by webguide** [icecoder/ICEcoder#591]
In addition to github support, could you please support even bitbucket or a generic remote git?

**Comment by mattpass** [comment]
I'd rather support git so it's general purpose and am looking into some PHP git implementations to make this happen. Soon hopefully!

**Comment by viharm** [comment]
Agree with @mattpass . If used as a generic _git_ client, this could work. I hope that #778 resolves this.

**Comment by mattpass** [comment]
This is exactly the plan - general git support and being worked on so closing this.
