### ISSUE TITLE
"Find" Behaviour since 5.2

### ISSUE THREAD

**Issue by raffiismail** [icecoder/ICEcoder#597]
Prior to 5.2 CMD+F or CTRL+F places focus on find textbox.
Now, focus only happens when textbox is empty. When not empty, Find behaviour highlights next occurance instead.

This means having to use mouse to change textbox value when we need to find a new string making it inconsistent with past behavious. While expecting to key in new search string, the highlighted occurence is modified instead. 

Plus using the mouse everytime for something we are used to using shortcuts defeats the purpose of having shortcuts in the first place.

**Comment by mattpass** [comment]
I added this as an improvement, tho I do see it creates inconsistent behaviour. It should maybe be reverted so CTRL+F always focuses on the find box.

The thinking behind this was:
CTRL+F would focus on the input box if empty.
If you have text selected when you hit CTRL+F it inserts that into the input box also.
CTRL+F will find the next occurrence if not empty.
CTRL+G will find previous occurrence.

Will need to think about what needs tweaking here so CTRL+F's only function is to focus on the find box.

**Comment by marcoczen** [comment]
From a closed thread - How do we we do a Find and Replace ? Currently i am doing it outside icecoder using kate or kwrite

**Comment by mattpass** [comment]
I've not heard anyone else mention this as an issue. If others do I can re-investigate but am OK with the behavior here.
