### ISSUE TITLE
Finishing FTP setup

### ISSUE THREAD

**Issue by mattpass** [icecoder/ICEcoder#616]
Finishing FTP usage

Lots done under issue #490 but some items and improvements remain, listed here for clarity:
- [x] UI needed for users to be able to set FTP details for as many accounts as they'd like (add/edit/remove) including reference name
- [ ] ~~Re the above point - don't store passwords locally, ask when connecting? Maybe a choice or strong warning here?~~
- [x] Canvas image hovers don't work with FTP held files - `Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.`. Need to allow cross-origin data in the case of sourcing over FTP.
- [ ] Support FTP over TLS/FTPS (see http://php.net/manual/en/function.ftp-ssl-connect.php)
- [ ] Operations same as saving local - paste file/folder, upload file(s), replace text in a file and check line endings
- [ ] Permissions modal screen won't show in FTP mode. Once done, also check you can change perms OK
- [x] Replace alert() with ICEcoder's message()
- [ ] New file won't save first time and may get path ref wrong (mix of local and FTP)
- [ ] Add in more error catching where needed?
- [ ] Check all file processes still work locally
- [ ] Dragging dirs/files into new tree positions doesn't always show up (is this the case for local also?)
- [ ] Newly created files need perms set also
- [ ] filemtime not available, need to use other creds to establish, currently sticking with 1000000
- [ ] Move file should get dir/file type instead of using hardcoded  $fileOrFolder = "folder";  plus JS function called to update FM should use param, not JS isFileFolder
- [ ] File MDT's not checked in FTP mode, always 1000000
- [ ] Can only delete 1 item at a time right now.
- [ ] Can't delete non empty dirs
- [ ] Full check through to complete

**Comment by mattpass** [comment]
Have been working on the FTP manager and it's almost ready to roll out so you can jump between FTP sites easily.

A question I'm pondering is - "is it OK to store all FTP details, including password?". User stored details would of course be within a .php file as with your other config details, however, when you choose an FTP site it would need to store your selection in the session during your usage. The session cookie is set to be stored in the tmp dir in ICEcoder.

The session cookies have ridiculously long names such as 'sess_AsC14FEvl4wOGWvyDLCizaZjUddlqR5IqfjYpcf9njSw43Wb,eNeZOjr1XCmvemj8Uw3SLcT9vvxbo1juIK,e2' so practically impossible to guess. However, should someone have a badly configured server and it show a list of files if someone browsed the /tmp dir, it would allow someone to view the list of session cookies, look into them and find full FTP creds.

It would be an annoyance to make the user input a FTP password each time, but would mean there isn't a full set of details there.

All thoughts welcomed.

**Comment by tcoombes** [comment]
Why not implement the password saving and let the user decide whether to use it or not? With a description of the above problems, then it passes the risk over to them?

**Comment by mattpass** [comment]
That's a pretty good solution - let them decide after providing risk info.

**Comment by tcoombes** [comment]
Yep. Then the people who don't mind the risk/can avoid it are able to remember the passwords and if anyone is unsure they can just not turn the feature on.

**Comment by mattpass** [comment]
Think this might be the solution - unless there's a better suggestion from anyone I'll maybe go with this.

**Comment by webguide** [comment]
I quote tcoombes but I do not understand the reason why expose passwords to
tmp. Couldn't you read the config file (with passwords) every time you need?
Anyway I am very happy if you release FTP support (is there the possibility
to backup versions automatically, isn't it?).
Thank you and good job

*Aldo Medri*


2016-07-19 10:54 GMT+02:00 Matt Pass <notifications@github.com>:

**Comment by mattpass** [comment]
Doh @webguide - think I'm having a dumb day!

Of course - we can store just an array reference for it in session and not the full creds! eg, you have 3 FTP sites entered into ICEcoder (details stored in your .php config file). Let's say you choose site 2, it can load the relevant creds for that from the config file each time. Absolutely no need to actually store the FTP creds in session, just a ref which can get the relevant creds to use from the config. Security concern averted.

Yep BTW, changes you make on FTP files are backed up on each save, just as per local server saving.

Thanks to you both. :-)

**Comment by mattpass** [comment]
OK, I'm pleased to announce that there's an FTP manager now that allows you to add, edit, delete and choose FTP sites to switch between easily:

![ftp](https://cloud.githubusercontent.com/assets/1311155/17053607/bb07a9a2-4ffa-11e6-813a-40a17fdefd3a.gif)

It'd be appreciated if people could check it out and let me know of any issues, else will be part of v5.6 due for release next week.

**Comment by mattpass** [comment]
Can't manage to get canvas data for images loaded over FTP due to CORS issue. Handling error instead and showing info message. Info here: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

**Comment by mattpass** [comment]
Have decided to remove FTP from ICEcoder as it's just not a modern solution to data transfer these days. Far better solutions out there and can be part of ICEcoder in future.
