### ISSUE TITLE
SVN Support

### ISSUE THREAD

**Issue by firstygoldfish** [icecoder/ICEcoder#644]
NOT AN ISSUE AS SUCH

SVN has been on the source tab for a while and being and old timer I still use SVN.
Is it still on the plan?

**Comment by mattpass** [comment]
It's on the cards at some point, but unfortunatelt not anytime soon. I'd like to get FTP and GitHub integration finalised first, plus user management and a few other bits, so is way down the list I'm afraid. If you do happen to code something re this I'd be happy to take a look, but may be a while till I look into this.

**Comment by mattpass** [comment]
Sorry, going to close this issue as it won't be something I work on.
