### ISSUE TITLE
File Explorer dont work with Edge

### ISSUE THREAD

**Issue by LordKBX** [icecoder/ICEcoder#650]
When I try to open a folder in the file explorer i received in console the error : 
"SCRIPT70: Permission denied
get-branch.php (99,3)"

**Comment by mattpass** [comment]
After a bit of digging into this issue, it seems to be an error/issue in Edge itself. ICEcoder works fine in Chrome, IE11 etc but Edge seems to have a few gremlins still they're trying to work out.

The line causing the error you see is https://github.com/mattpass/ICEcoder/blob/master/lib/get-branch.php#L455 - it doesn't want to get the parentNode of locNest. It's definitely a browser fault if it thinks it's OK to get a DOM elem in the parent frame but not the parentNode of that DOM item. It should be able to access any.

Seems to be a confirmed issue logged by users, so guess we'll have to wait for a fix there:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/?page=1&q=SCRIPT70%3A%20Permission%20Denied

In the meantime, I'd suggest having to use IE11 or Chrome.

**Comment by LordKBX** [comment]
I just tested it, I use Firefox Developper Edition with ICEcoder
