### ISSUE TITLE
Bitbucket Integration

### ISSUE THREAD

**Issue by alhoseany** [icecoder/ICEcoder#665]
Hi,
Is there is any plan to add bitbucket integration?

thank you.

**Comment by mattpass** [comment]
Not on roadmap for anytime soon but of course ICEcoder is open source so someone can give it a go. 😀

**Comment by webguide** [comment]
Bitbucket uses the same protocol as Github, but has free private accounts,
so me too, also I prefer Bitbucket.

2016-10-09 17:18 GMT+02:00 Matt Pass <notifications@github.com>:

**Comment by mattpass** [comment]
Both are Git based, but are online services each with their own API to handle Git tasks like read, commit, pull etc. It's implementing another API that takes the time. 😀

**Comment by viharm** [comment]
If used as a generic _git_ client, this could work. I hope that #778 resolves this.

**Comment by mattpass** [comment]
Similar to other closed issue, general git integration being worked on so would cover this. Closing.
