### ISSUE TITLE
Purchased Code but Editor keeps asking for Code

### ISSUE THREAD

**Issue by lenichols** [icecoder/ICEcoder#667]
I purchase the $10 license but every time I try to log in it keeps asking me for code, user and password. What am I doing wrong?

**Comment by mattpass** [comment]
Hmmm that is very weird. Has ICEcoder worked for you at all (ie you used it OK prior to purchasing a license?)

You may also want to view the test.php in ICEcoders dir in your browser (ie mydomain.com/ICEcoder/test.php) and check it passes the 3 tests fine.
