### ISSUE TITLE
Related to #505 - Undefined offset in file-control-xhr.php

### ISSUE THREAD

**Issue by moudsen** [icecoder/ICEcoder#669]
Since I'm using 5.7 I have the following error in my logs which typically keeps on appearing on a regular basis (also on refreshes) which is generating a lot of unhappy lines in my logs.
Let me know what you need about my setup and I will provide you asap.

[Tue Oct 25 20:42:54.109129 2016] [:error] [pid 1390] [client x.x.x.x] PHP Notice:  Undefined offset: 0 in /<hosts path>/<coder path>/lib/file-control-xhr.php on line 76, referer: <url>

**Comment by mattpass** [comment]
Think this was sorted a long time ago so closing.
