### ISSUE TITLE
Dir/File manger non ascii filename support

### ISSUE THREAD

**Issue by obarisk** [icecoder/ICEcoder#676]
Is it possible to make non ascii filename show and editor correctly?

for example

I create a file call È.html within the root path from ssh
the I open icecoder and look up the file on the file panel

for example
in server use bash to create a new file call È.html
  `touch È.html`
in icecoder file panel
it shows 
   .html
it could be editor within icecoder but could be saved

**Comment by mattpass** [comment]
OK will see if that can be covered.

**Comment by mattpass** [comment]
Have now covered this - it's no longer replacing characters with HTML entities and instead using the original characters, so working. (In your example È was being converted to &Egrave; when being made use of and a mismatch occuring).
