### ISSUE TITLE
very nice code viewer, but can u develop a "edit code online" function?

### ISSUE THREAD

**Issue by shinebay** [icecoder/ICEcoder#679]
This code viewer is very good, but I want to edit the code online, every time I tried and save, it will alert "Sorry, this file has change outside ICE editor", it can not edit code online, can you add the "edit code online" function ? thank you

**Comment by mattpass** [comment]
You can edit the code online, it's the main purpose of the editor. Not quite sure why it warns you the file has changed, but I'll check the code to see if I can avoid this false positive better.
