### ISSUE TITLE
Git intergration (not github)

### ISSUE THREAD

**Issue by dodedodo** [icecoder/ICEcoder#685]
Hi,

I'd love to try out icecoder but is there git intergration besides github? If so, does it support authentication somehow (user/pass)? I'd like to use my own private git server (gitbucket).

Cheers

**Comment by mattpass** [comment]
@dodedodo Unfortunately at this stage no, it's pretty heavily tied to GitHub's API. It would be great to make it also work with Git in general, but not done as yet.

**Comment by ScrumpyJack** [comment]
+1 for this, would love to have integration with ssh git server

**Comment by blackboxgeeks** [comment]
Is there any news on private git server integration?

**Comment by mattpass** [comment]
@blackboxgeeks not at present. Hopefully one day.

**Comment by viharm** [comment]
I believe this is not in the pipeline - #778 . Yay!

**Comment by mattpass** [comment]
Indeed, in the pipeline so closing this.
