### ISSUE TITLE
Can't open file with symbol # in the name

### ISSUE THREAD

**Issue by LordKBX** [icecoder/ICEcoder#695]
It's impossible to open a file with # in the name and after I try to open a file named "script#.js" you can't load an other file unless you reload the file explorer panel

**Comment by mattpass** [comment]
I never thought anyone would do that, as it could cause URL issues in browsers. Will look at fixing tho.

**Comment by LordKBX** [comment]
I do the work with the client desires in consideration

**Comment by mattpass** [comment]
Never thought of that as a use case but obviously could be! :-)

**Comment by mattpass** [comment]
This is now resolved. (ICEcoder wan't encoding URI components when passing filenames around and so trying to open a file named `blah#.js` it was being cut off as `blah` and being a file that doesn't exist, it of course won't open).

Filenames passed around in many places are now being URI encoded before being sent, so working fine.
