### ISSUE TITLE
Make ICEcoder work within an iFrame

### ISSUE THREAD

**Issue by mattpass** [icecoder/ICEcoder#699]
A few people have requested ICEcoder works within an iFrame but at the moment it won't due to many `top.ICEcoder` references which will need to be changed to relative references re their parent, so maybe `parent.ICEcoder` or simply `ICEcoder`.

**Comment by lexterror** [comment]
I would like to run ICEcoder in an iFrame

**Comment by mattpass** [comment]
> I would like to run ICEcoder in an iFrame

Agreed, would be nice and has been requested by users a lot. Should just be a case of changing the references mentioned above and testing everything.

**Comment by mattpass** [comment]
A PR has been started and contains a largely working version of ICEcoder but everything needs checking over and I'm sure plenty of bug fixes:
https://github.com/icecoder/ICEcoder/pull/804

**Comment by mattpass** [comment]
After a lot of work, ICEcoder is working well in an iFrame, within dynamicPaths branch and soon to be merged into master so closing this issue as done.
