### ISSUE TITLE
Add 'unlock code' section in Edit->Settings

### ISSUE THREAD

**Issue by mattpass** [icecoder/ICEcoder#710]
Would be a good place to allow users to enter unlock code.

**Comment by marcoczen** [comment]
Good. Make things easier.

**Comment by marcoczen** [comment]
Received my unlock code. So now I have to wait for a popup to appear before I apply it or can I just insert it into a file somewhere ? I think i have 10 more days before my v6.0 Beta trial expires?

**Comment by mattpass** [comment]
Yes, you can either wait until the 14 day trial period is over, or within ICEcoder, close all open documents and it displays a 'trial remaining' bar. There's a link there to go to the unlock screen early if you want to do it now.

**Comment by marcoczen** [comment]
Doing ... Must I add username etc ? Will this be published anywhere ?

**Comment by marcoczen** [comment]
Ok - unlock code added. It accepted and then presented me with the login page. After login - you still 
see;
"trial remaining"
11 days left - Unlock Now

So did the unlock work ?

**Comment by mattpass** [comment]
When you add your email address and unlock code It's not sent anywhere or published anywhere, only used to unlock ICEcoder.

If you have multiple users, it may not currently apply the unlock via the UI right now (is why we need an Edit -> Settings system as you suggested).

If it still shows the trial remaining bar, it's not been applied for that user. Open any lib/config-*.php files in ICEcoder and put in youremail and the unlock code where I've indicated YOUREMAIL and XYZ...

```
<?php
$ICEcoderUserSettings = array(
"versionNo"		=> "6.0 beta",
"licenseEmail"		=> "YOUREMAIL",
"licenseCode"		=> "XYZ",
...

**Comment by marcoczen** [comment]
Ok doing.

Actaully I am the only user. I have a desktop at home and a windows laptop. So its 2 machines.

**Comment by mattpass** [comment]
That's fine, your unlock code is per user (ie, you), not per install or machine. So please feel free to install and use on any many computers as you like under your details.

**Comment by marcoczen** [comment]
All ok. Thanks Matt.

**Comment by mattpass** [comment]
No need to do this anymore as ICEcoder is free, doesn't require unlock code. Closing.
