### ISSUE TITLE
Minimap - Anyway to switch it off ?

### ISSUE THREAD

**Issue by marcoczen** [icecoder/ICEcoder#711]
Minimap - Anyway to switch it off ?
I would like to have my full screen for editing ....
Hehehe ...

**Comment by mattpass** [comment]
Not at present, but it's a good idea for a feature so tagging this as something to be done in future.

**Comment by marcoczen** [comment]
Noted. Thanks.

**Comment by ScrumpyJack** [comment]
+1

**Comment by hostbrook** [comment]
+1

**Comment by levkach** [comment]
Sort of barbarian workaround is "kill" it in CSS. You won't get the autosize though

**Comment by mattpass** [comment]
The upcoming release of ICEcoder (v8) will have the minimap dropped to avoid excess CPU/RAM usage and give more room for editing. Done in `dynamicPaths` branch.
