### ISSUE TITLE
Illegal Character and Undefined Offset in IceCoder

### ISSUE THREAD

**Issue by marcoczen** [icecoder/ICEcoder#713]
The below seen in apache error log. Any ideas ?

PHP Notice:  iconv(): Detected an illegal character in input string in /srv/www/vhosts/test/ice_coder6/lib/settings-common.php on line 206, 

PHP Notice:  Undefined offset: 1 in /srv/www/vhosts/test/ice_coder6/lib/file-control-xhr.php on line 139,

**Comment by mattpass** [comment]
PHP 'notice' errors are typically minor issues for unhandled cases that you need be considered.

I would only really be able to investigate this and handle the issue it was having at the time if I reproduce the exact same steps (ie, same content, same actions you were performing etc). No huge concern here (compared to say a PHP 'warning' error or 'fatal' error), but I would like to know these things so I can clean up odd cases by consider what's causing these notices and mitigate.

**Comment by marcoczen** [comment]
Roger that.

**Comment by marcoczen** [comment]
Just would like to add that these bugs appear in both a linux / windows box with either a firefox or chrome browser.

Recent versions of browsers used.

**Comment by marcoczen** [comment]
Update.

i have temporarirly added a "@" to the offending lines in file-control-xhr.php, etc.

**Comment by mattpass** [comment]
Have changed `iconv` to `mb_convert_encoding` to resolve the 1st issue mentioned. Re the 2nd issue mentioned, it's hard to say what would cause this, would need exact content that was being saved at the time. If there's a reproducible example it can be looked at. Thanks for reporting the issues a couple of years ago.
