### ISSUE TITLE
Grey strip on selected line obscures text underneath.

### ISSUE THREAD

**Issue by abalter** [icecoder/ICEcoder#720]
This is for dark themes. I've tried a number of them. The grey strip makes it very hard to see what is underneath. Depending on the color scheme, this can be keywords or values. Attached is an image with the monokai theme in a css file. I can't make out the number value at all.

Perhaps a more opaque band? Something the user can set?

![monokai](https://user-images.githubusercontent.com/5349876/29379602-d95799d4-8277-11e7-9708-aaa8f9415c4d.PNG)

**Comment by mattpass** [comment]
That's a fair point - could do with looking into this and tweaking it to fix this and similar issues on other themes.

**Comment by mattpass** [comment]
The grey strip was changed for a black strip a while back so closing.
