### ISSUE TITLE
Keyboard mapping for "find."

### ISSUE THREAD

**Issue by abalter** [icecoder/ICEcoder#721]
In the editor, I can hit <kbd>CTRL</kbd>+<kbd>f</kbd> which pops me into the search box. Subsequently, if I hit the same key combination, the editor searches for the next instance. In most editors (and other search systems, such as web pages, acrobat reader, etc.), that key combination pops you back into the search box.

I might suggest using a different keystroke to maneuver between search results? Perhaps <kbd>CTRL</kbd>+<kbd>F</kbd>, or some combinations including "n" for next and "p" for previous.

**Comment by mattpass** [comment]
This has been mentioned in another issue I believe and a valid point. I think when it was raised previously there was some decision making to be done re the keys that users would use most often.

**Comment by mattpass** [comment]
In retrospect it may be different to other programs but I think this is OK. People haven't mentioned it as an issue for a couple of years now so I'll close this issue.
