### ISSUE TITLE
Firefox v52.x - v56.x (64-bit) Linux - CPU Usage  exceeds 100%

### ISSUE THREAD

**Issue by marcoczen** [icecoder/ICEcoder#729]
Guys,

Any insight on why FIrefox spikes 100+ % cpu usage ? Files approx 500 lines are enough to cause such a spike ...

**Comment by marcoczen** [comment]
Minimap works here but the CPU spike is a killer ....

**Comment by marcoczen** [comment]
The problem still exists with Firefox v56.0.2 (64-bit)

**Comment by mattpass** [comment]
The minimap could be a bit intensive and I should be able to look at this and make it more efficient hopefully. Adding an option to turn the minimap on/off is still an issue to cover also.

**Comment by marcoczen** [comment]
Thanks MattPass x 10000. I appreciate all the work and support you have given.

I have now just gone back to desktop solutions.

On Windows:  Notepad++ and NppFTP for Remote Editing via SSH
On Linux      :  Kate and Konqueror for Remote Editing via SSH

Both approached are rock solid and are able to edit files in a mixed environment with zero issues.

**Comment by mattpass** [comment]
@marcoczen No problems. I'll keep plugging away and improving things. Hope to catch you again one day soon and thanks for all the help and feedback 👍
