### ISSUE TITLE
Chrome - Minimap still squashed ? v 62.0.3202.89 (openSUSE Build) (64-bit) - Fix from  Issue #717 does not work

### ISSUE THREAD

**Issue by marcoczen** [icecoder/ICEcoder#730]
Man, oh man ..

Minimap is totally unusable in the latest version of chrome ...

**Comment by marcoczen** [comment]
No cpu spike here but the minimap is a distraction ....at least we should be able to switch it offfff !!!!!

**Comment by mattpass** [comment]
Agreed and is is down as an issue somewhere I think. Would be good to switch on/off for sure, or maybe just automatically switches for smaller screens, that would be better.

**Comment by gohrner** [comment]
Is this issue about the problem shown in the following screenshot, or should I open a new bug about this:

![image](https://user-images.githubusercontent.com/26199042/48311873-91e78080-e5a6-11e8-89cb-9c6dd62d3198.png)

**Comment by mattpass** [comment]
@gohrner This is very odd - I'm on Chrome 70 also and looks fine to me. It seems to not be setting the font size on the minimap. What OS are you using and do you see any JS errors in the dev tools Console tab?

**Comment by gohrner** [comment]
> @gohrner This is very odd - I'm on Chrome 70 also and looks fine to me. It seems to not be setting the font size on the minimap. What OS are you using and do you see any JS errors in the dev tools Console tab?

Thanks for your reply - I just had another look into it and it (mainly) seems to have been a configuration problem on my side.

For whatever reason a rather big "minimum font size" was configured for my Chrome. I now lowered it as far as possible and the minimap looks *much* better this way, but the lines still overlap slightly.

That's probably as good as it can get in Chrome?

![image](https://user-images.githubusercontent.com/26199042/49477417-32833600-f81d-11e8-840e-890caac51e72.png)

**Comment by mattpass** [comment]
Closed as the above issue was due to unusual setting on min font size in Chrome and issues re wrapped lines, turning minimap off automatically and more noted to be handled in https://github.com/icecoder/ICEcoder/issues/674
