### ISSUE TITLE
Code Lines being Jumbled Up - Related to Issue #716

### ISSUE THREAD

**Issue by marcoczen** [icecoder/ICEcoder#731]
Old problem - Deleted lines , code lines being jumbled up ... Really crazy ?

**Comment by marcoczen** [comment]
Update - I can confirm that this happens in a Linux (64 bit Firefox v56) environment as well as a Windows 7 ( 32 bit Firefox v54 ) environment.

Happens when we delete lines above multi-line code lines.

**Comment by mattpass** [comment]
It's so strange as no one else has this issue anymore. You have tried a fresh v6.0 final (not beta), from website or GitHub? Should be resolved there.

**Comment by cedricgeffroy** [comment]
I think I had the same issue with 6.0 final. 
Chrome Win 10

**Comment by mattpass** [comment]
Any chance you could send a dummy/sample file (to info@icecoder.net) and the exact steps you're taking to reproduce this?

**Comment by marcoczen** [comment]
@mattpass ...

Steps to reproduce -> Edit source php file using a browser on a Window 7 box. Close. Goto a Linux environment - another location - edit php files .... Repeat multiple times and BANG....source code gets corrupted by ghost lines ( especially lines that i deleted , code moved yp by deleting empty lines).

The whole idea of using a web based editor for me was to ensure i have the same editor when i am working from windows and when i have to use Linux. Thats was why i liked IceCoder.

It was nice while it lasted but its too dangerous an issue - phantom code/ghost code/. 
Thanks MattPass x 10000.

I have now just gone back to desktop solutions.

On Windows:  Notepad++ and NppFTP for Remote Editing via SSH
On Linux      :  Kate and Konqueror for Remote Editing via SSH

Both approached are rock solid and are able to edit files in a mixed environment with zero issues.

**Comment by mattpass** [comment]
@marcoczen Again, thanks for all the great feedback. Will concentrate on this issue also now we're underway into the New Year. Catch you soon :-)

**Comment by rob0d** [comment]
Hi Matt, 
I keep having this (or very similar) issue in v6.0.
Lines that seem deleted and saved, reappear after the file was opened again.
Sometimes lines get duplicated too.

**Comment by mattpass** [comment]
Haven't seen this issue crop up for a year or two now so closing.
