### ISSUE TITLE
403-Error on certain php-commands

### ISSUE THREAD

**Issue by shufschmid** [icecoder/ICEcoder#732]
Hi. I'm using ICEcoder to edit Wordpress-Templates. I like it a lot, but already several times, I came across this bug: As soon as I include certain PHP-commands, for example the "preg_match"-function, the editor doesn't let me save the file anymore, in the console it's written because of a 403-error. I played around a bit and I'm really not understanding the behavior. If I write "preg" instead of "preg_match", I can save, as soon as I add the underscore, the error occurs. I had the same problem with certain wordpress-functions, I don't remember all but sure there was a problem with $wpdb->get_row, but not with $wpdb->get_results. 

My workaround is now: I edit the line with the preg_match-command in the wordpress-editor, save the file, load it and I'm able to go on coding in ICE. As long as I don't touch the line with the preg_match-command. 

Do you or does anyone have an idea what could be causing this issue? Thanks for your advice and keep on coding ICEcoder, it's fantastic!

**Comment by mattpass** [comment]
Apologies for delay in responding on this issue. I can't think of what would cause this other than your web host? Have used ICEcoder for years, preg_match a lot and never had any issues. Did you resolve this 403 problem in the end?
