### ISSUE TITLE
weak password hashes

### ISSUE THREAD

**Issue by DanielRuf** [icecoder/ICEcoder#736]
password_hash or password_compat with bcrypt should be used instead of sha1, md5 and so on

https://github.com/icecoder/ICEcoder/blob/3a10a84c48f6b4491af35eea16f75e9bb61d10b4/lib/settings-common.php#L112-L120

**Comment by mattpass** [comment]
Agreed, should be upgraded.

**Comment by mattpass** [comment]
Migrated to password_hash with Bcrypt algorithm, closing.
