### ISSUE TITLE
Question: Share Link to edit file inside icecoder

### ISSUE THREAD

**Issue by skerbis** [icecoder/ICEcoder#744]
Is it possible to send an developer a link inside icecoder, so that the linked file will be opened after LogIn?

**Comment by mattpass** [comment]
Sorry for delay in replying. To answer your question - yes, if you use ICEcoder's rich API.

If they're logged into ICEcoder in the same location as you, and there's a file `index.html` you want them to see, get them to open dev tools with F12, go to the Console tab and paste this then hit Enter:

```
ICEcoder.openFile('/index.html');
```

**Comment by mattpass** [comment]
Extra tip - if you want to be clever, ICEcoder has a `processes` dir where you can specify your own custom code to trigger on various events. You could add this code into say the processes/on-load.php:

```
<script>ICEcoder.openFile('/index.html');</script>
```

...this file will then open whenever anyone logs in. If you have ICEcoder in multi-user mode you could target it to a specific user. eg if their username is `mike89`, you could have this to be more specific:

```
<?php
if ($_SESSION['username'] === "mike89") {
  echo "<script>ICEcoder.openFile('/index.html');</script>";
}
?>
```

**Comment by skerbis** [comment]
cool thx

**Comment by skerbis** [comment]
is there a way to make links like /icecoder?openFile=/xyz.html ? without writing javascript for each dynamic request?
