### ISSUE TITLE
File Manager broken as of Firefox 63

### ISSUE THREAD

**Issue by rob0d** [icecoder/ICEcoder#745]
Hi Matt,

I'm having problems with the left hand folder navigation since Firefox was updated to V63. I'm not sure it it's a Firefox bug or something is not exactly right with the CSS. Please see the attached screenshots with  FF 62.0.3 (works fine) and FF63 (doen't work). 
Each item on the list is missing the beginning and the icons are incorrect in some cases.
I haven't checked if new version of Chrome has the same issue or if it's specific to FF.

Would you be able to look at it?

Thanks,

Rob

This is what it looked like when it worked:
![icecoder_ff62](https://user-images.githubusercontent.com/5948834/47491839-93454900-d843-11e8-84e3-4d9e5c0208ac.PNG)

This is  what it looks like now:
![icecoder_ff63](https://user-images.githubusercontent.com/5948834/47491860-9dffde00-d843-11e8-8b4f-85df1af74099.PNG)

**Comment by toastbrotch** [comment]
my quickfix: in lib/file-types.css remove the line 22 by changing it to:
```
/*! margin-top: -19px; */
```

**Comment by rob0d** [comment]
That helped. Thanks :+1:

**Comment by mattpass** [comment]
Fixed, see this issue for info and link to commit which fixes.
