### ISSUE TITLE
undefined function iconv()

### ISSUE THREAD

**Issue by beenotung** [icecoder/ICEcoder#747]
When I click a file from the left menu, the console shows this error. It works if I click on folder but not files.

[Thu Nov 15 09:21:06 2018] 127.0.0.1:58056 [500]: /lib/file-control.php?action=load&file=|files.php&csrf=594984bef13c3ca9e961f52776aef402&lineNumber=undefined - Uncaught Error: Call to undefined function iconv() in /home/beenotung/workspace/github.com/mattpass/ICEcoder/lib/settings-common.php:208

**Comment by mattpass** [comment]
Hmmm, thanks - I'll try and add something in to handle this.

**Comment by mattpass** [comment]
I think this is part of PHP by default, but have added an if condition around its use. Done and closing.
