### ISSUE TITLE
ICEcoder page is not showing

### ISSUE THREAD

**Issue by Aslamfarook** [icecoder/ICEcoder#748]
Hi,
I am facing issue with ICEcoder page.While runnig the setup file in virtual machine docker container it is working.But when i am try to execute the same thing in azure container instance the page is keep on loading there is nothing appear.please help to resolve it
![screenshot from 2018-12-01 17-00-05](https://user-images.githubusercontent.com/44917470/49327717-a659e000-f58a-11e8-8f41-b6395caf6536.png)

**Comment by mattpass** [comment]
This looks like it's having massive issues with PHP (at a guess). Clicking the links on the far right hand side next to each error should hopefully give some clues re the issue.
