### ISSUE TITLE
AntiVirus Avast Virus Detected

### ISSUE THREAD

**Issue by JFOC** [icecoder/ICEcoder#749]
Detected a virus inside.
![screen shot 2018-12-14 at 13 17 53](https://user-images.githubusercontent.com/240271/49986544-e1a0d980-ffa2-11e8-8c54-0246818fc819.png)

**Comment by mattpass** [comment]
Thanks for the reminder. Added a XMR revenue generating script, decided not to proceed with it but forgot to remove from demo page. Removed now.
