### ISSUE TITLE
Unable to Load ICEcoder in IFrame

### ISSUE THREAD

**Issue by gogularaja** [icecoder/ICEcoder#750]
Hi Team,

I am trying to load ICECoder in the IFrame. For that, i have done the following changes.

1) Changed the below line in "headers.php"

Changed Line : 

header("X-Frame-Options: allow-from *");

2) After this, i am able to login into ICEcoder. But it is showing only the loading page.

![selection_122](https://user-images.githubusercontent.com/14348828/50077526-a1439480-020a-11e9-8a93-1d1359a7df7b.png)

Can you please guide us in solving this issue.

 If possible can you please the file names? So that we can & work on it.

**Comment by mattpass** [comment]
ICEcoder isn't presently setup to run from within an iFrame. There are many references to `top.ICEcoder`, which would end up looking to your top level frame and not the iFrame so breaking horribly. I suspect the issues you're seeing above are just a side effect of that.

If you amend all top.ICEcoder references to no longer look to top, you'll probably find it runs fine. However, there's going to be 100's of them to amend.

**Comment by mattpass** [comment]
PS - if you do remove all references to `top.` and get it working perfectly in an iFrame, I'd gladly accept a pull request so it runs in an iFrame for people in the future, it's been requested a few times before.

**Comment by gogularaja** [comment]
Hi Mattpass,

Thanks for your response.

If possible, can you please provide any one sample change that needs to be done in a file.

Eg: change for any one API.

So that we can proceed further to complete it.

**Comment by mattpass** [comment]
@gogularaja I'd suggest it's a repo wide find and replace. Try replacing

```top.ICEcoder```

with simply

```ICEcoder```

(ie, removing the `top.`) it may start working in an iFrame then, or at least get you much closer to it working.

**Comment by jesus1989** [comment]
Hi, @gogularaja I have exactly the same problem, did you find a solution to your problem or at least another alternative to ICEcoder that allow framing that is still in development?
Thanks.

**Comment by mad-tunes** [comment]
I've just done a find/replace with top.ICEcoder/ICEcoder on everything and still have the flipping box and working... forever when using Organizr and an iframe.
It doesn't seem to break anything when not going through organizr though.

**Comment by mattpass** [comment]
A PR has been started and contains a largely working version of ICEcoder but everything needs checking over and I'm sure plenty of bug fixes:
https://github.com/icecoder/ICEcoder/pull/804

**Comment by mattpass** [comment]
The work on this is done so it's working well within an iFrame now, see dynamicPaths branch and soon to be merged into master.
