### ISSUE TITLE
Sorry - problem with file/folder requested

### ISSUE THREAD

**Issue by ctuxboy** [icecoder/ICEcoder#751]
Hello,

When go to **File -> Properties** then it shows a popup with this error:

**Sorry - problem with file/folder requested**

(Following the manual installing ICEcoder and set the permissions to 775)

**Comment by mattpass** [comment]
Apologies for delay in responding on this issue. Think this issue is system/env dependent as I've not come across this error. If you're able to confirm OS etc I may be able to investigate.

**Comment by MuhShalah007** [comment]
same issue, how to solve it?
