### ISSUE TITLE
Bad CSRF Token

### ISSUE THREAD

**Issue by jasonarmbrecht** [icecoder/ICEcoder#754]
```
Bad CSRF token. Please report the error info at https://github.com/mattpass/ICEcoder so it can be fixed.

CSRF issue:
REQUEST: 
SESSION: 057d5dfdecf8113c31d8aec1f46f29fc
FILE: /code/index.php
GET: array ( '/' => '', )
POST: array ( )
```

Occurred on version 6.0 of ICEcoder. 
First-time login screen appears, enter a password then this pops up.

Server is running centOS 7, php7.2, nginx (SSL/HTTPS)

Cheers!

**Comment by mattpass** [comment]
Try going to /icecoder/test.php and run the test suite. Something likely up with your PHP sessions.
