### ISSUE TITLE
[CSS] images in file tree misaligned

### ISSUE THREAD

**Issue by sfnprg** [icecoder/ICEcoder#755]
I'm testing ICEcoder in my server and noticed that images in file tree are misaligned. I'm referring to the icons (es. document, folder, php logo, etc.) next to the filename.
This seems to affect all tree levels but it's easy to notice in a subfolder.

The "culprit" seems to be `margin-top: -19px;` assigned in CSS to `.fileManager LI.pft-directory::before, .fileManager LI.pft-file::before`. I'm on Firefox/Ubuntu.

**Comment by geloda** [comment]
It is the same in Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by sfnprg** [comment]
Later noticed that removing that margin will misalign images on Chrome (Win and 
Linux).
So seems that margin-top: -19px is necessary in Chrome but not in Firefox

**Comment by mattpass** [comment]
Thanks for the bug report and fix here, you're absolutely right.

When the CSS hack was written it worked fine, but over the years, it applied to other browsers such as Firefox and IE. I've tweaked the CSS hack here so it works in all browsers as expected, by only applying to Chrome and Safari, as it should:

https://github.com/icecoder/ICEcoder/commit/d61e263e0e11da84a1b7b674bdcc8b526f615f52

Closing the issue as resolved now.

**Comment by macserv** [comment]
@mattpass I don’t have Chrome installed, but I’m now seeing misaligned icons in Safari, Firefox, and Brave on macOS (10.15 Catalina DB6 19A536g).

I’ve submitted a PR #772 which addresses this issue by removing the following code from `lib/file-types.css`:

- `@media` rule (fixes the alignment in Firefox and Brave).
- `display: block;` in `LI.pft-directory:before` (fixes Safari, no effect on FF / Brave)


Browser | `master` | `#772`
---------|--------- | ------------
Firefox 69 b16 | ![FirefoxDE69-b16](https://user-images.githubusercontent.com/1233992/63616007-9e2c4f80-c5b4-11e9-8544-8fad934e49a2.png) | ![FirefoxAfter](https://user-images.githubusercontent.com/1233992/63617649-003a8400-c5b8-11e9-9b8d-39bb7c549d9e.png)
Safari 13.0 | ![Safari13 0-15608 2 2](https://user-images.githubusercontent.com/1233992/63616001-9bc9f580-c5b4-11e9-9eb6-d1a08ad11e6f.png) | ![SafariAfter](https://user-images.githubusercontent.com/1233992/63617635-f6188580-c5b7-11e9-8910-aa43849c285b.png)
Brave 0.68.131<br>(Chr. 76.0.3809.100) | ![Brave0 68 131-76 0 3809 100](https://user-images.githubusercontent.com/1233992/63615507-8902f100-c5b3-11e9-9eae-2a70faf32895.png) | ![BraveAfter](https://user-images.githubusercontent.com/1233992/63617675-0e88a000-c5b8-11e9-8db7-f4521cc5937b.png)

**Comment by mattpass** [comment]
@macserv thanks for the fix and review of what it fixes above. Confirmed it was also causing an issue in Edge and Brave (on Win) and this fixes it on those too while not affecting others (eg Chrome on Win).
