### ISSUE TITLE
Shared install?

### ISSUE THREAD

**Issue by lordspace** [icecoder/ICEcoder#757]
how to share the install codebase and set a password?
is there a way to have a custom config file?

**Comment by mattpass** [comment]
ICEcoder is fine for trusted teams of devs to work on but not for unknown users. If you want to have a multi-user setup for your team, open the `lib/config___settings.php` file on your install and change the `multiUser` setting from `false` to `true`.

Get all your team members to visit your ICEcoder install and they will need to enter a username as well as a password. When you want to have no more team members register, change `enableRegistration` from `true` to `false`.

Now users (your team members) can only log in, no more registrations are possible.

Hope this helps.
