### ISSUE TITLE
Opening file ... never opens

### ISSUE THREAD

**Issue by paulfeakins** [icecoder/ICEcoder#762]
Files can be opened from a local source but not via FTP.

The files and folders are all displayed on the left.

There are no errors in the console but this is in the error-log.txt:

```
[29-May-2019 09:40:15 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function toUTF8noBOM(), 1 passed in /home/pauldev/public_html/icecoder/lib/file-control.php on line 104 and exactly 2 expected in /home/pauldev/public_html/icecoder/lib/settings-common.php:180
Stack trace:
#0 /home/pauldev/public_html/icecoder/lib/file-control.php(104): toUTF8noBOM('<?php    \ndefin...')
#1 {main}
  thrown in /home/pauldev/public_html/icecoder/lib/settings-common.php on line 180
```

**Comment by paulfeakins** [comment]
Problem is:
/lib/file-control.php:104 calls toUTF8noBOM with just 1 parameter when the function expects 2.

I adjusted the function to make the second parameter default to null:
/lib/settings-common.php:180

From:
function toUTF8noBOM($string,$message) {
To: 
function toUTF8noBOM($string,$message=null) {

And now files load over FTP.

Seems like a bug in the latest version?

**Comment by paulfeakins** [comment]
P.S. it's a shame icecoder won't let you edit its files from within itself as I could have used it to fix this!

**Comment by mattpass** [comment]
> Seems like a bug in the latest version?

That certainly does seem like a bug and the reason why you wouldn't get file contents! I'm OK with adding the `=null` fallback but think I should fix the couple of places we call upon `toUTF8noBOM` without a 2nd param. (It's calling on it with 1 param also here https://github.com/icecoder/ICEcoder/blob/master/lib/file-control-xhr.php#L272).

So think I'll add your fallback but also explicitly set the 2nd param on those couple of usages also.

Thanks for the investigation & find!

**Comment by mattpass** [comment]
> P.S. it's a shame icecoder won't let you edit its files from within itself as I could have used it to fix this!

Have considered showing the ICEcoder dir in the file manager a few times rather than hide it, but in the end felt it didn't make sense to show it, plus it'd be easy to make a mistake, break the PHP and perhaps not be able to login/use it.

That said, I do use ICEcoder to build newer versions of itself. Perhaps it could be added as an option should people want to see it in the file manager? :-)

**Comment by paulfeakins** [comment]
> Thanks for the investigation & find!
No problem, suggested fixes sound good!

> Perhaps it could be added as an option should people want to see it in the file manager?
Having it as an option in the settings seems like a good idea to me :-)

**Comment by mattpass** [comment]
Have set the 2nd arg in the couple of places it was used without and also a `$message=false` fallback as it should be a true/false bool passed in. Thanks for the report, done and closed.
