### ISSUE TITLE
Error 403 on installation

### ISSUE THREAD

**Issue by HydrexHD** [icecoder/ICEcoder#763]
When I install ICEcoder in /var/www/html, I become an 403 error message. My System is Linux Debian 9 with Nginx and PhP 7.3

**Comment by mattpass** [comment]
> When I install ICEcoder in /var/www/html, I become an 403 error message. My System is Linux Debian 9 with Nginx and PhP 7.3

403 is a `forbidden` error and would be something server related. Likely dir/file permissions. You may find useful info in PHP's error logs?

**Comment by HydrexHD** [comment]
Where are the PhP error logs allocated?
