### ISSUE TITLE
FTP / Opening and Saving

### ISSUE THREAD

**Issue by intradesign** [icecoder/ICEcoder#770]
Hi there,
I just tested icecoder and ran into two problems.

1) Opening files via FTP did not work so I used the workaround mentioned here: https://github.com/icecoder/ICEcoder/issues/762

2) Saving files shows error message that file has been changed outside icecoder which is definitely not the case.

Confirming to open diff view shows empty file on the left (file from server) and the original content on the right (unsaved file). Pressing cmd+s to save the file results in double content in the saved file.

This seems to be a very old issue as I fount mentions from back in 2017... Is this a configuration issue?

Thanks and best regards

**Comment by mattpass** [comment]
Have decided to remove FTP from ICEcoder as it's just not a modern solution to data transfer these days. Far better solutions out there and can be part of ICEcoder in future.
