### ISSUE TITLE
CSRF check failed while test.php passed

### ISSUE THREAD

**Issue by Seiken-2ch** [icecoder/ICEcoder#773]
Greetings.
I can't login/set password in both my old and new ICEcoder installation after I switched to a new Debian server. It always returns a CSRF issue like this:
```
CSRF issue:
REQUEST: string1
SESSION: string2
FILE: /icecoder/lib/login.php
GET: array ( )
POST: array ( 'password' => 'Some_random_password', 'submit' => 'set password', 'disableFurtherRegistration' => 'true', 'checkUpdates' => 'true', 'csrf' => 'string1', )
```
It totally passed TEST 1 and 2 in test.php (not 3 since it can't generate the setting file). What could be the problem here?

**Comment by mattpass** [comment]
A fresh install may help as a lot of changes have been happening lately, including the config now being stored in the `data` dir and not `lib`. It's work in flux and if any further trouble, grab the last stable release (v6.0): https://github.com/icecoder/ICEcoder/releases/tag/v6.0

**Comment by mattpass** [comment]
Newer versions of ICEcoder have been released and this issue isn't raised anymore so hopefully resolved. The test.php file has also now been removed and code from it absorbed into the setup process as part of checks done. Closing.
