### ISSUE TITLE
Sidebar UI bug (Icecoder 6.0) (Linux)

### ISSUE THREAD

**Issue by heavylildude** [icecoder/ICEcoder#776]
![icecoder-bug](https://user-images.githubusercontent.com/18643376/65131152-eeb69180-da28-11e9-9f4e-2a2dc9fdf937.png)

I'm using the icecoder 6.0 using webkit-based browser and/or mozilla based browser on Linux (Linux Mint 19) and the sidebar went huhah..

Was trying to access from Chrome - Windows 7 and it looks okay, anyone with the same issue? I think its related to latest browser update on Linux

**Comment by mattpass** [comment]
@heavylildude hmmm, there was an update re this about 3 weeks ago that could cause this issue?
https://github.com/icecoder/ICEcoder/pull/772/files

The fix seemed to resolve the problem on many browsers. I wonder if the previous version works for you tho? You could try copying the contents of this https://github.com/macserv/ICEcoder/blob/d61e263e0e11da84a1b7b674bdcc8b526f615f52/lib/file-types.css into lib/file-types.css to see it resolves the problem?

Let me know if reverting this file works or not?

**Comment by mattpass** [comment]
@heavylildude oh, as a sidenote question - did you download from the website or latest from GitHub. If it was from the website, that doesn't contain the fix yet and this GitHub repo does.

**Comment by heavylildude** [comment]
@mattpass aaah https://github.com/macserv/ICEcoder/blob/a3f78f78d9b281020d3aa8de2e7a4b1bf72b5620/lib/file-types.css this one works for me.. 

To be honest I've been using ICECoder for a while (abt 6 months) I downloaded it from the website, at first I thought its just linux fonts or whatever, but it was okay on Firefox, but then as time goes it went crooked on all linux browser.. that URL just fixed it!

Anyhow beautiful products! Many thanks mate!

**Comment by mattpass** [comment]
@heavylildude great, glad to hear the updates fixed it. Also glad you're enjoying ICEcoder (version 7 should be out in a 7-8 days and even more awesome!) 👍
