### ISSUE TITLE
File manager, file tree layout problem

### ISSUE THREAD

**Issue by uree** [icecoder/ICEcoder#779]
I'm consistently seeing (across browsers - chrome, firefox, chromium, edge - and operating systems - windows, ubuntu) a jumbled up file tree, with files and folders covering each other up.

![Screenshot from 2019-09-26 13-02-27](https://user-images.githubusercontent.com/12390599/65683622-f9db7400-e05d-11e9-88c6-307bc1c5ec32.png)

**Comment by mattpass** [comment]
@uree Try grabbing the latest code from this repo. If you grabbed from website, it'll be the 6.0 version and this repo contains 6.0+ with fixes. New version 7.0 also out tomorrow.

This solved issue will be use till then:
https://github.com/icecoder/ICEcoder/issues/776

**Comment by uree** [comment]
thank you i will try this shortly and report back

**Comment by mattpass** [comment]
This issue should be resolved in the new v7.0 so closing.
