### ISSUE TITLE
Make password rules more obvious

### ISSUE THREAD

**Issue by mattpass** [icecoder/ICEcoder#782]
Some users don't notice that there are password rules lighting up, make it a little more obvious.

**Comment by herbert256** [comment]
I second this, I needed to read this issue to understand what was going on.

**Comment by mattpass** [comment]
Have done a couple of things to help on this - firstly, made the rules shake 4 x more visually and for slightly longer, plus the password input field shakes along with them: https://github.com/icecoder/ICEcoder/commit/0793c2fd639de501ee6c55e2edc9775d81dea588
