### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by LostAndDead** [icecoder/ICEcoder#798]
I get a 500 Server error whenever I try to access it, I've tried some of the previous issues fixed about this on the GitHub and to no success. I used a shared hosting platform by tsohost if that is of any importance to what might be the issues. I have contacted them and they are unable to help with this issues as their logs provide to information on this event

**Comment by mattpass** [comment]
Unfortunately a 500 error is very general server error type, would need to see log info to be able to identify what the cause may be. However, in the past I've found 99% of the times I've helped other users in ICEcoder setup who face 500 errors, it's a server setup/usage issue (eg permissions, maybe PHP sessions etc) and not code related to ICEcoder.

Anyway, the reason for the 500 would most likely be in logs and would need that info to help advise. Hope you can get that.
