### ISSUE TITLE
Recognize different extensions as a language

### ISSUE THREAD

**Issue by arelas** [icecoder/ICEcoder#799]
Sorry if this has be posted elsewhere, but I was unable to find it.  I have Python files that end in the extension .mpy

How would I tell ICEcoder that those files are Python files and have the editor open them as such?  Ideally, something like this would be configurable one day, but for now I would just like to find what code to change to allow this manually.

**Comment by mattpass** [comment]
Hey @arelas - no worries, it's not a question that's been asked yet.

The best thing for anyone to do if they want to add a new language in ICEcoder is read the steps at https://icecoder.net/manual#addingExtraLanguages. As you're not really adding a new language but just wanting to add a new file extension the most important thing is to search for `coffee` (isn't it always?!) :-) as it's a specific enough word and the name of the language and file extension. Then you can add in new items as needed.

There's only 4 files that need updating really, but I've done this for you as I'd like to see `.mpy` in ICEcoder as file extension, so you can just pull the latest code from this repo and you're good to go.

Updates if you're interested to see what changed:
https://github.com/icecoder/ICEcoder/compare/65002056247c3efa0f2ad8f2c21d930e6f643971...master
