### ISSUE TITLE
Cannot open files without filename extensions

### ISSUE THREAD

**Issue by viharm** [icecoder/ICEcoder#800]
Hi, firstly congratulations on a slick tool. Thanks.

I have recently setup an instance of _ICEcoder_ on my home server (_openmediavault_ 4.1 using _Debian_ 9) and have created a workspace folder inside the _ICEcoder_ installation directory for my projects. I have configured the root as `workspace`. My projects are setup in separate subfolders within this `workspace`. 

When I try to open files without a filename extension like `LICENSE` or `VERSION`, I get the following error:
```
Sorry, /workspace/ProjectName/Code/Current/LICENS does not seem to exist on the server
```

Note that the error message removes the last character of the filename (`LICENSE` → `LICENS`).

Am I doing something wrong?

**Comment by viharm** [comment]
I tried this with the demo instance at http://demo.icecoder.net/ICEcoder/

I attempted to create a file in root called `VERSION`
![image](https://user-images.githubusercontent.com/2663937/72068359-c7881680-32dc-11ea-897e-13796c099685.png)

However it failed with the following error.
![image](https://user-images.githubusercontent.com/2663937/72068372-d078e800-32dc-11ea-8849-d8616486c484.png)

Note that the error message removes the last character of the filename (`VERSION` → `VERSIO`).

**Comment by mattpass** [comment]
Thanks @viharm for the great bug report and glad you like ICEcoder.

This was indeed a bug, but not quite for the reason you thought (as you could make a new file without an extension such as `BLAH` just fine). The issue actually is that ICEcoder uses placeholder text of `[NEW]` when making a new file and should be trimming that at the end of data it passes around. However, `rtrim` is mistakenly being used, so will remove any of the characters [, N, E, W or ] from it and and finding your filename is `VERSION` trim the N character from the end.

`preg_replace` should have been used instead so we truly do remove `[NEW]` from file path references and not those single uppercase characters from legitimate file names.

The bug fix has been committed and can be seen here:
https://github.com/icecoder/ICEcoder/compare/278e34c3d4364afcd6a8673c531f5566ef187027...master

Thanks again for the report and trust this fixes the issue for you.
