### ISSUE TITLE
How to Inject JavaScript into All Pages

### ISSUE THREAD

**Issue by 4424dev** [icecoder/ICEcoder#803]
Hello, following https://github.com/icecoder/ICEcoder/issues/792, I already have it on a server.

I am wondering if there is a file I can edit that would run JavaScript on all loaded pages. Websites like 000webhost.com add a banner to each page which can break ICEcoder, but it can be removed with JavaScript.

**Comment by mattpass** [comment]
Work is being done at present on the `dynamicPaths` branch which allow ICEcoder to work within an iFrame which may help solve your issue.
