### ISSUE TITLE
Visual Theme/Styles for Editor

### ISSUE THREAD

**Issue by ozett** [icecoder/ICEcoder#805]
Is it possible to change the syntax-highlighting style for the editor?
some other themes? maybe based on file-ending?

i find the theme of atheos very readable. 
https://github.com/Atheos/Atheos

is there a way to port/exchange this?

**Comment by mattpass** [comment]
> Is it possible to change the syntax-highlighting style for the editor?
> some other themes? maybe based on file-ending?
> 
> i find the theme of atheos very readable.
> https://github.com/Atheos/Atheos
> 
> is there a way to port/exchange this?

Yes, above the files on the left there are File | Edit | Source | Help options. Go to Edit > Settings and in the modal that pops up, click the Style tab and in here you can style the editor, including changing to any of the 51 themes available.

Atheos isn't a theme that's available, but if you want to port it over provide a PR for it I'd be happy to consider it. Themes are simply CSS files and those 51 themes can be found in https://github.com/icecoder/ICEcoder/tree/master/CodeMirror/theme

Take a look at any of those and see the CSS classes you could provide styles for if you want to port over Atheos. Hope this helps.

**Comment by ozett** [comment]
thx for quick and detailed reply. i will consider to port the themen next days..
👍

**Comment by ozett** [comment]
i think making a theme is bit above my head...

i wish icecode could simply switch through the lots of text-color-styles simply within the editor.
i wish it would be easy to make within atheos or icecoder a colorsheme for the tags in the editor.

until than i will try some icecoder  styles as i cannot  see what  an how to port the color-scheme for the tags in the editor .. 😢 

![image](https://user-images.githubusercontent.com/5937811/75868694-b8b76f00-5e08-11ea-816f-a7eff1d20926.png)

**Comment by mattpass** [comment]
> i think making a theme is bit above my head...
> 
> i wish icecode could simply switch through the lots of text-color-styles simply within the editor.
> i wish it would be easy to make within atheos or icecoder a colorsheme for the tags in the editor.
> 
> until than i will try some icecoder styles as i cannot see what an how to port the color-scheme for the tags in the editor .. 😢
> 
> ![image](https://user-images.githubusercontent.com/5937811/75868694-b8b76f00-5e08-11ea-816f-a7eff1d20926.png)

Oh, well there's no plans to allow you to custom create your own theme using a user interface. If other people want the same it can be added into future plans.

For now, my best suggestion is to copy https://github.com/icecoder/ICEcoder/blob/master/CodeMirror/theme/icecoder.css to a new file, atheos.css, set all colors in that file to #000 so everything is black to start with. Then put the same content into both editors side-by-side and then start changing each of the #000 values to a color, see what changes in ICEcoder, look at what you see in Aethos and then set the same color.

I've done this approach for a theme I liked elsewhere that ended up being the base for icecoder.css. Might take a short while and you may not get an exact match, but you can get close if you wish to spend the time doing this.
