### ISSUE TITLE
config file missing from lib folder in version 7

### ISSUE THREAD

**Issue by arpitset** [icecoder/ICEcoder#806]
I just installed ICECoder and I want multiple users, but I am unable to find the config file in lib folder. The home page is saying for multiple user please go to /lib/config-setting.php page, but unable to find that page.

**Comment by mattpass** [comment]
@arpitset ahh that's an old path, it's in a new place (will amend this for next release of ICEcoder).

You can find the file now in `data/config-settings.php` and amend this line from false to true then reload your browser:

`"multiUser"		=> true,`

Thanks for letting me know of the old incorrect path!

**Comment by mattpass** [comment]
Amended to correct paths in alllanguages in `dynamicPaths` branch.
