### ISSUE TITLE
Compatibility error

### ISSUE THREAD

**Issue by petrmachcz** [icecoder/ICEcoder#818]
Do not work with PHP 5.3.

**Comment by mattpass** [comment]
@petrmachcz that's correct - the current version of ICEcoder moved onto PHP 7+ as PHP 5.3 is no longer supported by PHP devs anymore - https://www.php.net/eol.php (they stopped supporting it 5 and a half years ago).

It's highly recommended to upgrade your PHP version but if you simply can't and must stick with 5.3, you can use a previous version of ICEcoder which supports 5.3:
https://github.com/icecoder/ICEcoder/releases/tag/v6.0

**Comment by petrmachcz** [comment]
OK, but in README.md is:

> The only requirement is to have PHP 5 available (5.3 recommended).

**Comment by mattpass** [comment]
> OK, but in README.md is:
> 
> > The only requirement is to have PHP 5 available (5.3 recommended).

Thanks for letting me know, updated.
