### ISSUE TITLE
Issue with passwords that generate a '$' in the password hash string

### ISSUE THREAD

**Issue by moudsen** [icecoder/ICEcoder#825]
Found and eliminated an issue with passwords that after hash generation include a '$' sign in the generated value. This value is incorrectly read back by the config script caller as the $ is interpreted as a (non-existent) string:

[25-Apr-2020 11:22:28 Europe/Amsterdam] PHP Notice:  Undefined variable: n9StJfGvcosqJgMuYjHd9 in <coderdir>/data/config-<name>.php on line 21

Solution: (sorry I'm currently not able to provide Pull myself; will try later this week)
Adjust /lib/settings.php with a simple STR_REPLACE line before the password is written into the config file (line 194 in version 7.0):

```
// If we are on the login screen and not logged in
} elseif (!$_SESSION['loggedIn']) {
        // If the password hasn't been set and we're setting it
        if ($ICEcoder["password"] == "" && isset($_POST['submit']) && (strpos($_POST['submit'],"set password")>-1)) {
                $password = generateHash(strClean($_POST['password']));
                $password = str_replace('\$','\\$',$password);
                $settingsContents = getData("../data/".$settingsFile);

```
If you encounter this issue, you can adjust the password manually in your /data/config-....php by simply adding the '\' before every '$'.

**Comment by moudsen** [comment]
Just found out the issue is fixed in the current master branch already; use the above for your own benefit if you're not updating between versions (before 7.1) ... :-)

**Comment by mattpass** [comment]
As you mentioned, this is fixed, but useful to keep the above info for anyone before next version is out (which will be v8 actually, as there's some huge changes happening, so won't be v7.1, but v8!) :-)

**Comment by mattpass** [comment]
We store data in a serialized format now and don't have this issue, plus v8 beta is out any day now so happy to close this issue.
