### ISSUE TITLE
Can only save once, then must refresh

### ISSUE THREAD

**Issue by kristopherdick-clc** [icecoder/ICEcoder#827]
When saving a document, the following errors show in the console and a refresh is required to save again.

> Uncaught SyntaxError: Unexpected token . in JSON at position 0
> at JSON.parse (<anonymous>)
>     at XMLHttpRequest.h.onreadystatechange (ice-coder.min.js?microtime=1588275876.4875:137)

and 

> Uncaught (in promise) SyntaxError: Unexpected token . in JSON at position 0
> Promise.then (async) |   |  
> -- | -- | --
>   | (anonymous) | @ | ice-coder.min.js?mic…e=1588275876.4875:7
>   | setInterval (async) |   |  
>   | init | @ | ice-coder.min.js?mic…e=1588275876.4875:5
>   | onload | @ | (index):76

**Comment by mattpass** [comment]
I've also seen this issue and couldn't get to the bottom of the problem. A fresh install of latest version did resolve the issue tho.
