### ISSUE TITLE
NGINX  - No PHP Session

### ISSUE THREAD

**Issue by Lord-Windy** [icecoder/ICEcoder#832]
Hi All,

I'm having a devil of a time getting this working. I'm getting the error:

![image](https://user-images.githubusercontent.com/5555847/82878732-3c53a880-9f7f-11ea-80e8-0d471fdd5d0e.png)

The Hello was from me trying to debug the problem. I'm running Nginx and I can get both PHP and sessions going after tweaking. I know this issue will be one of my configuration. Everytime I look I find something else that could potentially be the issue. But I've run out of ideas now and I don't know enough about php to try and debug the issue so here is a dump and I hope that this isn't an actual problem. Everything is chmodded to 775 for now. 

![image](https://user-images.githubusercontent.com/5555847/82888551-cb1af200-9f8c-11ea-914f-3c912ec0d9b8.png)

This is my attempting to connect via just using the folder directory as suggested in the setup manual. I had to set up a special location

![image](https://user-images.githubusercontent.com/5555847/82879643-9143ee80-9f80-11ea-8b9c-b113e697cd35.png)

If I use index.php

![image](https://user-images.githubusercontent.com/5555847/82888723-0ae1d980-9f8d-11ea-90f8-ff36292bcf6d.png)

My config file for Nginx

![image](https://user-images.githubusercontent.com/5555847/82878684-27771500-9f7f-11ea-80c7-3d5cc6fa917d.png)

Showing that sessions is on. I have also confirmed that things are placed into the folder.

https://pastebin.com/vw7pH8tf

My config file for php (php.ini)

**Comment by Lord-Windy** [comment]
![image](https://user-images.githubusercontent.com/5555847/82890234-31a10f80-9f8f-11ea-97fb-345346e9f454.png)

You can shoot me now. This was because I needed to 757 (or I accidentally did 755 instead of 775). I fixed it by setting everything to 777.

**Comment by mattpass** [comment]
@Lord-Windy no problems and glad to see you resolved your issue. :-)

I'd recommend looking into chown and chgrp going forward to set the owner and group rather than set everything to 777, it's a bit safer.

Other than that, have fun! 👍

**Comment by Klemich** [comment]
Hi, it turns out I have a similar problem on Nginx : 
 chown : www-data:www-data
 chmod : files are in 644 and folders in 755

I'm quite reluctant to set everything to 777

It says that the "mime type" of the css files is not the right one, but I think that's just an effect of the access to the css folder ?
![image](https://user-images.githubusercontent.com/16766404/134650312-154cab9d-48b3-44be-bda1-5d2be3788cc3.png)

**Comment by mattpass** [comment]
@Klemich I'd say this is either a session or path issue rather than a permissions issue as for each CSS file it's loading login.php.
