### ISSUE TITLE
can't update config file: data/config-172_xx.php

### ISSUE THREAD

**Issue by bright-1iu** [icecoder/ICEcoder#834]
when i visit the sub-dir URL in browser, I encountered an error:
can't update config file: data/config-172_xx.php Please check write perimssions on data dir and reload page.
I have tried setting write permissions (757 or 775 or 755 depending on your system) on the 'data', 'lib', 'plugins', 'test' and 'tmp' folders, but still the same error
ICEcoder Version 7.0

**Comment by mattpass** [comment]
@bright-1iu sorry for delay in replying - have been busy hugely overhauling ICEcoder and working towards a v8 release.

If you were still having trouble, you could try grabbing latest version from this repo as a fresh install and try again.

I'll close as I believe all is OK, but if not please reopen issue.
