### ISSUE TITLE
Not able to create an index.php

### ISSUE THREAD

**Issue by mattpass** [icecoder/ICEcoder#841]
It's been reported that trying to create an index.php returns a prompt to inform you the file is already there, when it isn't. I'm not able to reproduce this issue, but need to look into it. The same issue doesn't occur if you try to create an editor.php or files.php so it's not conflicting with ICEcoder itself it seems.

Steps:

	To create a new file I use the "FILE" menu 
	NEW FILE...
	then type the name of new file in popup.

	I have the same issue when right clic on /[ROOT] then NEW FILE
	And same issue when using the + button on top of page, close to tabs position.

**Comment by mattpass** [comment]
I've never been able to reproduce this - does this work OK for you @cedricgeffroy?

**Comment by cedricgeffroy** [comment]
Yes it's working now. You can close.

**Comment by mattpass** [comment]
Will do. No idea why index.php specifically wasn't working. Glad it is now tho 😀
