### ISSUE TITLE
Server message sticks if you change tab while saving

### ISSUE THREAD

**Issue by mattpass** [icecoder/ICEcoder#847]
Report from user:

If you CTRL+S a file and switch to another file before the saving has finished, the file stays as unsaved forever... red x in tab and "Saving" grey banner bottom left stays. 

Only option is to close the tab and accept the "Close without saving" popup.

I don't know if it's all the time, but most of the time (all the time?) I have to F5 the chrome tab where I have icecoder to be able to open that file again.

**Comment by mattpass** [comment]
I can reproduce the tab still having a red x in the tab, probably because of the doNext requests re ICEcoder.selectedTab (which of course has changed):

```
"ICEcoder.openFileMDTs[ICEcoder.selectedTab - 1] = \"1593017662\";(function() {var x = ICEcoder.openFileVersions; var y = ICEcoder.selectedTab-1; x[y] = \"undefined\" != typeof x[y] ? x[y] + 1 : 1})(); ICEcoder.updateVersionsDisplay();if (ICEcoder.previewWindow.location && ICEcoder.previewWindow.location.pathname && -1 === ICEcoder.previewWindow.location.pathname.indexOf(\".md\")) {ICEcoder.previewWindowLoading = false;ICEcoder.previewWindow.location.reload(true);ICEcoder.checkPreviewWindowLoadingInt = setInterval(function() {if (\"loading\" !== ICEcoder.previewWindow.document.readyState && ICEcoder.previewWindowLoading) {ICEcoder.previewWindowLoading = false;try {ICEcoder.doPesticide();} catch(err) {};try {ICEcoder.doStatsJS('save');} catch(err) {};try {ICEcoder.doResponsive();} catch(err) {};clearInterval(ICEcoder.checkPreviewWindowLoadingInt);} else {ICEcoder.previewWindowLoading = \"loading\" === ICEcoder.previewWindow.document.readyState ? true : false;}}, 4);};cM = ICEcoder.getcMInstance();cMdiff = ICEcoder.getcMdiffInstance();if (ICEcoder.updateDiffOnSave) {cMdiff.setValue(cM.getValue());};ICEcoder.setPreviousFiles();setTimeout(function(){ICEcoder.indicateChanges()}, 4);ICEcoder.savedPoints[ICEcoder.selectedTab-1] = cM.changeGeneration();ICEcoder.savedContents[ICEcoder.selectedTab-1] = cM.getValue();ICEcoder.redoTabHighlight(ICEcoder.selectedTab);ICEcoder.serverMessage(); ICEcoder.serverQueue(\"del\", 0);ICEcoder.switchMode();"
```

Haven't seen the server message staying as "Saving" but likely related.

Also response from settings.php on save also:

```
<script>parent.parent.ICEcoder.serverMessage();parent.parent.ICEcoder.serverQueue("del",0);</script>
```

**Comment by cedricgeffroy** [comment]
Easier to reproduce with large files as it takes more time to save the file.

**Comment by mattpass** [comment]
> Easier to reproduce with large files as it takes more time to save the file.

Yep, am testing with a file of 25k lines. I've just pushed some work in progress which I think resolves this but is by no means finished or fully tested: https://github.com/icecoder/ICEcoder/commit/9d1e2549557dfb873ce0b5fe3168c2182bf6272c

If you have a few minutes, feel free to pull and try the latest, but be careful, not necessarily finished yet, really a WIP.

**Comment by mattpass** [comment]
Yeah it was to do with ICEcoder.selectedTab (which has changed after request to save was made), so on return journey from that is actioning on tab you switch to.

Handled this by finishing WIP in above commit - when saving it now sends along with it the tab number to target correct tab on return journey.

Works fine so closing as done.
