### ISSUE TITLE
Unable to move a file

### ISSUE THREAD

**Issue by cedricgeffroy** [icecoder/ICEcoder#849]
When I try to move a file sometimes it doesn't prompt the popup confirmation and nothing happens. 
Sometimes the popup confirmation is prompted but the destination folder is missing the subdirectory folder name.

Also I was not able to move from a subdirectoy to the root directory.
Either no confirmation prompted or confirmation prompted but nothing happens after.

**Comment by cedricgeffroy** [comment]
More generally, it would be great to have a UX improvement when moving files or directories. What about adding a border 1px around the destination folder when hovering it, right before dropping the element you are moving.

**Comment by mattpass** [comment]
Hmm, I'm generally avoiding borders in the new UI but highlighting needed for sure, prob changing background color of dest folder.

**Comment by mattpass** [comment]
Drag a file somewhere, then try and try it somewhere else, causes JS error.

**Comment by mattpass** [comment]
This is mostly sorted now, only a little more work to tidy things up but generally working really well now.

**Comment by mattpass** [comment]
Can now also right click to rename a file and in the dialog prompt, enter a new path for it too.

If you simply rename the file, it stays in dir. If it's a dir that's open, the child items path IDs are updated also.

If you during the rename of a file you set a new path (and new name if you wish), it'll handle that. If it's a dir it'll appear in new location as closed dir of course.

**Comment by cedricgeffroy** [comment]
Do handle the case when the file is open and you change its name and path? :)

**Comment by mattpass** [comment]
> Do you handle the case when the file is open and you change its name and path? :)

Yep, checked that and working well.

**Comment by mattpass** [comment]
Everything here covered I believe:
- Moving file dialog prompt always shows
- Moving file does make it move, doesn't error/nothing happen
- Dialog doesn't show incorrect info
- Can drag from a dir to root level and vice vera
- Dir you are dragging into highlights in orange
- Can drag onto other files in dir, the dir hightlights in orange
- Moving a file that's open in a tab updates its location
- Can rename a file's path in dialog prompt and the tab updates its location
- Can rename a file in dialog prompt and the tab updates its filename also
- Can rename update and update both path and filename and works as above 2 points

**Comment by mattpass** [comment]
Related tho different subject - can delete a file or dir and if there's a file open that has now been deleted (due to dir/file deletion) the tab is closed.

I think everything here is working well now so closing.
