### ISSUE TITLE
Unable to save a newly created file

### ISSUE THREAD

**Issue by cedricgeffroy** [icecoder/ICEcoder#850]
I create a new file and start typing code.
When I hit CTRL+S, it says the file has been modified outside ICEcoder.
Panel diff shows empty file for other version. 

I close the new file, lose what I typed. 
Open it again, file is empty. 
Now I'm able to edit and save the file.

**Comment by mattpass** [comment]
With no files open in ICEcoder and viewing the server info screen, what do you see under the **Server name, OS & IP:** heading?

I see this for instance:
Server name, OS & IP:
localhost    PHP 7.4.7 Development Server    Unknown

It's the middle part I'm most interested in as I think I need to make adjustments there.

**Comment by cedricgeffroy** [comment]
Server name, OS & IP:
www.mydomain.com    nginx/1.10.3    xxx.xxx.xxx.xxx

**Comment by mattpass** [comment]
> Server name, OS & IP:
> [www.mydomain.com](http://www.mydomain.com) nginx/1.10.3 xxx.xxx.xxx.xxx

Excellent - I'm looking at wrong data, I'll try a fix and get back to you v soon :+1:

**Comment by mattpass** [comment]
> > Server name, OS & IP:
> > [www.mydomain.com](http://www.mydomain.com) nginx/1.10.3 xxx.xxx.xxx.xxx
> 
> Excellent - I'm looking at wrong data, I'll try a fix and get back to you v soon

@cedricgeffroy can you pull latest commits and see if that sorts things?

The display for you should now be:
`www.mydomain.com Linux xxx.xxx.xxx.xxx`

...and hopefully you don't have the save issues?

**Comment by cedricgeffroy** [comment]
Hi Matt, 
Just pulled last version.
I looks like you fixed this issue!

**Comment by cedricgeffroy** [comment]
I am now able to create a new file and save it right after without error.

**Comment by mattpass** [comment]
Woot! Making real progress now 😀
