### ISSUE TITLE
Request: ability to edit .json files

### ISSUE THREAD

**Issue by moudsen** [icecoder/ICEcoder#887]
Is it possible to configure file types like ".json" that can be edited with ICEcoder.
Currently .json is interpreted as "an external file" and will not allow me to edit it, while ".js" does open an editor window?

**Comment by mattpass** [comment]
Needed to add a MIME Type exception for application/json, done in https://github.com/icecoder/ICEcoder/commit/6210eca0bdd32eb02658de1999e5958172d19af2
