### ISSUE TITLE
Uncaught TypeError: Return value of ICEcoder\\System::createDirIfNotExists() must be an instance of ICEcoder\\void

### ISSUE THREAD

**Issue by andreescocard** [icecoder/ICEcoder#929]
Fatal error
Using php 7.0.30 in ubuntu

**Comment by mattpass** [comment]
This issue was raised by someone else, they resolved it by upgrading PHP from 7.0 to 7.1:

https://github.com/icecoder/ICEcoder/issues/915

Will look into fixing this error but the error may be resolved if you can upgrade to PHP 7.1.

**Comment by andreescocard** [comment]
i imagined that i should upgrade php, in my case that was not an option with other applications running together on the same server. I guess that requirements should be updated, thanks for clarification

**Comment by mattpass** [comment]
No problems. However, this issue will be fixed (so it works on 7.0, I've done something that requires 7.1). Will fix rather than up requirements. 👍

**Comment by mattpass** [comment]
Found the issue was using the void return type, which isn't introduced in PHP till 7.1.

Fixed in https://github.com/icecoder/ICEcoder/commit/0b75351b1fa3870bf03cabb25f61b34e7ec83a86
