### ISSUE TITLE
Problems with Cookies

### ISSUE THREAD

**Issue by atorresbr** [icecoder/ICEcoder#943]
Is there a way to solve this problem with Cookies? I LOGIN on another browser and I didn't have this problem.

image problem: https://www.facebook.com/photo?fbid=1537954856405625&set=a.121994628001662

**Comment by mattpass** [comment]
Hmmm, it may be a session cookie storage location problem if it's a Wordpress site and ICEcoder also (as ICEcoder stores the PHP session in one (the tmp dir) and WordPress in another and so conflicts may be occuring. Something for me to look at fixing I think. Closing your browser windows and viewing either the WordPress site or ICEcoder would probably work fine, but not both.

**Comment by mattpass** [comment]
You might be able to get around this issue in the meantime by commenting out this line:
https://github.com/icecoder/ICEcoder/blob/master/lib/settings-common.php#L26

If you close all browser windows, open 2 and view your WP site in one tab and ICEcoder in another without this error occuring?

**Comment by atorresbr** [comment]
> You might be able to get around this issue in the meantime by commenting out this line:
> https://github.com/icecoder/ICEcoder/blob/master/lib/settings-common.php#L26
> 
> If you close all browser windows, open 2 and view your WP site in one tab and ICEcoder in another without this error occuring?

I'll debug more via wordpress and cPanel, I don't want to comment on the lines because of security, but I had already checked this option in the IceCoder documentation

**Comment by mattpass** [comment]
Aside from not enforcing the /tmp path to save session data now, I've also set things up so the session cookie should be able to run alongside another PHP app (eg Wordpress)'s session cookie, as they'd work in isolation: https://github.com/icecoder/ICEcoder/commit/a5678eba26d403b522c3206b025a718b81eebcf4

Hope this resolves the problems here. Pls reopen if not.
