### ISSUE TITLE
Overprint about panel in every panes

### ISSUE THREAD

**Issue by Singman33** [icecoder/ICEcoder#952]
Hi,

In all my panels, I have an overprint of the starting "About" panel... Hard to see but very disturbing.
![image](https://user-images.githubusercontent.com/6518183/103152916-d89b9300-478c-11eb-9d6c-82170455ffe6.png)
![image](https://user-images.githubusercontent.com/6518183/103152887-8f4b4380-478c-11eb-9f19-34fe7c3d9ead.png)

**Comment by mattpass** [comment]
Which theme are you using? (We introduced a load of new themes and standards in ICEcoder 8).

May be something to adjust if looking particularly obvious with lighter themes.

**Comment by mattpass** [comment]
Had a look into this and found it was on the "iplastic" theme shown above. Also had the same "very slightly transparent" effort on "emacs strict" and "made of code" themes.

Removed from all 3 themes in: https://github.com/icecoder/ICEcoder/commit/de3e46d5eeda3b256d2285ea0e70728df54a5ba4
