### ISSUE TITLE
Find Conflicts with CTRL+ commands

### ISSUE THREAD

**Issue by raymondsalas** [icecoder/ICEcoder#955]
Hi, not sure if this is a bug in v8.0. But if a text is present in the "Find" text box, CTRL+ commands seem to act weird in the code editor box. This only happens if the find text was entered in a different file.

Steps to recreate:
1. open 2 files (File A and File B)
2. enter find text in File A
3. go to File B and try one of the examples below 

Example 1:  If ctrl+a is used at the middle of the code editor box, it will go to the top of the code and deselect it self. So it's hard to do select all (ctrl+a) then copy (ctrl+c).

Example 2: If ctrl+shift+right_arrow or just shift+right_arrow just deselects the text after highlighting it in a few nanoseconds.

While I'm at this, I would also like to request if it is possible to have the option to disable or reassign some keyboard shortcuts then return to their native behavior. I'm specifically requesting this for ctrl+backspace since at times I would like to do a word backspace, but the behavior in ICEcoder is to return to the last opened/selected tab.

Thank you so much for your hard work. I'm a user and fan since v5.x.

**Comment by cedricgeffroy** [comment]
OMG !! This is an issue I also have and that is VERY annoying. 
Only way to stop this is to reload the chrome tab.

@mattpass remember I talked about it in one of our exchanges.
But I wasn't able to reproduce it. 

@raymondsalas I tried to reproduce it with your steps but wasn't successful. 

I installed a key logger to see if it catches the combination.
But it is definitely related to some of those:
- ctrl + a
- ctrl + shift + arrows left/right
- ctrl + arrows up/down
...

**Comment by raymondsalas** [comment]
@cedricgeffroy yeah. Before, I used to reload the tabs before but I realized that when you simply remove all text in the find text box, the behavior will return to normal (in my case at least).

As for reproducing this, if it helps, I am using Opera 73.0.3856.344 Portable with PHP files. Although I just tried it again with more than 2 PHP files and not all ICEcoder tabs have the issue. It seems to occur with newly opened files/ICEcoder tabs? I mean by newly opened = tabs that were not automatically opened at ICEcoder's initialization.

**Comment by cedricgeffroy** [comment]
I confirm that removing the text in the search box fixes the issue! 
What a relief! Thank you @raymondsalas 
Maybe it will help @mattpass finding the root cause.

**Comment by mattpass** [comment]
@raymondsalas @cedricgeffroy I looked into this a few months ago plus today and just simply can't recreate the problem. Everything seems to work as expected.

Maybe something is now fixed - could you pull the latest version of ICEcoder and try again. If it's a reproducible issue still now, could you take a quick video to demo the problem? (That really helped on the obscure "go to line" issue a few months ago - couldn't recreate the problem till I saw your video).

Hopefully it's fixed now tho. Let me know if you can. :-)

**Comment by raymondsalas** [comment]
Thanks for looking into this @mattpass ! as requested, here is a link to the video. I used the latest version here at Github. https://filebin.net/nprb8z6vw6hgs8w7

Link will expire within a week. Let me know if I need to reupload.

Also, on a different issue. I am having instances where tabs are unresponsive when clicked. It's not a full memory/cpu issue since the code editor is working properly. It's just the tabs that are unresponsive at times. Unfortunately, I am unable to determine the exact reproduction steps for the freezing tabs issue as of this moment. I'll just open another issue thread when I am able to determine the steps.

**Comment by mattpass** [comment]
Brilliant demo, thanks @raymondsalas - can clearly see exactly what's happening for you. I haven't managed to recreate the problem as yet, but could be something to do with large files being loaded and a race condition (timing) problem? I'll try to recreate & examine code more to see if I can track this down - looks like a really annoying issue. 👍🏼

**Comment by mattpass** [comment]
OK, great news - I can reliably reproduce it now! It's not a timing thing as I suspected, actually happens on auto-opened files on load as well as opened manually. Is down to a couple of lines I added and not sure why I added them LOL.

Am just reviewing if I can remove them and will put in a commit to fix shortly. :-)

**Comment by raymondsalas** [comment]
Haha! Maybe it's one of those days when our fingers are faster than our brain. Glad to know that you were able to quickly track it down. Looking forward to your fix and will be happy to test it for you.

**Comment by mattpass** [comment]
I think so, yeah! 😄 In short - it finds whatever is in the find box in realtime as you keypress - great for live matches & results.

But for some silly reason I had it set to clear selections on keypress (that'd include CTRL, shift, alt, arrow keys etc). So the problem wasn't obvious unless there were 0 results and you were doing something other than adding characters into the document (which clears selections of course) - control (CTRL etc) keys make the problem very obvious under this 0 results scenario.

Definitely wasn't a great bit of code to add, I can't think of any reason to clear selections on 0 results when you keypress and is more of a benefit to keep selections anyway (plus avoids this deselection issue!).

So, I believe I've fixed things in this commit https://github.com/icecoder/ICEcoder/commit/2d245f2da8e2cbf50b4bf8b25946037489e85cd9 - if you could pull latest from GitHub and confirm all is OK for you too now?

**Comment by raymondsalas** [comment]
Ohh that's why. I've also been playing around with icecoder.js to track it down. I initially thought it was an element focus issue, but wasn't able to find anything related to focus that might be causing it. Anyway, on initial testing, the fix works awesome! I'll test it within a week and comment here if I find anything odd related to it. If not, we can probably close this. Thanks again, @mattpass !

**Comment by raymondsalas** [comment]
No related issues experienced after a week. Closing...
