### ISSUE TITLE
https plugin install error

### ISSUE THREAD

**Issue by donmortis** [icecoder/ICEcoder#958]
If just https domain created Apache config, then drop 500 internal server error. If created non https domain or redirect to https, its working!

**Comment by mattpass** [comment]
@donmortis Sorry for delay in replying. I don't believe this is a http vs https issue, but your PHP installation (for the _"https domain created Apache config"_) doesn't have the `ZipArchive` class. I tried a localhost setup which has a basic PHP installation and doesn't have this, then when installing I alsoget a error 500:

```
PHP Fatal error:  Uncaught Error: Class "ZipArchive" not found in /server/path/icecoder/lib/plugins-manager.php:34
```

If you look in your PHP error logs, you may see the same issue? It indicates what you need - `ZipArchive` (as ICEcoder will obtain the zip for the plugin and attempt to unzip it, but can only do that if `ZipArchive` PHP class is available).

To avoid others having this issue, I've added a new commit to check this class exists first and if not will show an error message: https://github.com/icecoder/ICEcoder/commit/0850127d2b89c66f9bcf3e576a8907aa784bd929#diff-181a5a2c6f468c1e834b1af3e6712cd8b53134f10cb76eb0945aca812b09b9feR222-R223
