### ISSUE TITLE
Config file name issue after domain change

### ISSUE THREAD

**Issue by wmdhosting** [icecoder/ICEcoder#960]
i have  config-dev-domain.php on dev domain

After site is online and change from dev domain to production
icecoder looks forconfig data in  config-production-domain.php

Is there any way to make this allways same name...   
so no need to change everytime. 

or any other idea..

**Comment by mattpass** [comment]
That's an interesting requirement. You could change this line to set your own file name:
https://github.com/icecoder/ICEcoder/blob/bc589549f374052798cb4fa92b38e34f73d8c9ab/lib/settings.php#L64

**Comment by wmdhosting** [comment]
ok thx..  :)
