### ISSUE TITLE
"Find" doesn't work in Dutch and German

### ISSUE THREAD

**Issue by StijnBousard** [icecoder/ICEcoder#961]
Typing something in the 'Find' box, immediately results in higlighted results in English (and French and Italian), but not in Dutch or German. In these languages, nothing happens at all.

No errors appear in the Console tab of the browser's dev tools and no error.log is found in the data dir.
(The only error that appears hundreds of times, but also in English, is "Unchecked runtime.lastError: The message port closed before a response was received.")

I'm using Chrome v89.
The webserver is a Linux machine with Apache 2.4 and PHP 7.2.34, and I'm using the latest version of ICEcoder, v8.0.

**Comment by StijnBousard** [comment]
I found the cause and the/a solution.
The text string "this document" occurs twice in the language file icecoder/lang/dutch.php, once on line 94, and once on line 258, but with a different translation. The t(ranslate) function in icecoder/index.php and in icecoder/assets/js/icecoder.js can't deal with the two translations.

So replace line 258:
-        "this document"                            => "dit bestand",
into
+        "this document"                            => "dit document",

The same goes for the german language file icecoder/lang/german.php
Replace (the untranslated string in) line 258:
-        "this document"                            => "this document",
into
+        "this document"                            => "dieses Dokument",

**Comment by mattpass** [comment]
@StijnBousard thanks for the report & tracking down this issue. I've covered what you mentioned and more after a quick review, in this commit: https://github.com/icecoder/ICEcoder/commit/f27905404bb36529fe643104ad38e1a77b3da4e5

Thanks again!

**Comment by StijnBousard** [comment]
Hi Matt, 

My pleasure! 

Would you like me to review the Dutch lang files? Some translations are missing, others are too long (breaking the two columns in the General Settings for example)? 

Kind regards 

Stijn 


Van: "Matt Pass" ***@***.***> 
Aan: "icecoder/ICEcoder" ***@***.***> 
Cc: "StijnBousard" ***@***.***>, "Mention" ***@***.***> 
Verzonden: Maandag 5 april 2021 12:09:44 
Onderwerp: Re: [icecoder/ICEcoder] "Find" doesn't work in Dutch and German (#961) 





[ https://github.com/StijnBousard | @StijnBousard ] thanks for the report & tracking down this issue. I've covered what you mentioned and more after a quick review, in this commit: [ https://github.com/icecoder/ICEcoder/commit/f27905404bb36529fe643104ad38e1a77b3da4e5 | f279054 ] 

Thanks again!

**Comment by mattpass** [comment]
> Would you like me to review the Dutch lang files? Some translations are missing, others are too long (breaking the two columns in the General Settings for example)?

That would be great if you could @StijnBousard! Yes please.

**Comment by mattpass** [comment]
Will close this as original issue sorted.
