### ISSUE TITLE
Cannot select "Cobalt" theme

### ISSUE THREAD

**Issue by moudsen** [icecoder/ICEcoder#962]
Cobalt theme is available in the assets/themes directory but does not show when using Settings/Style.

Fix: editor.php, line 46:
Add `, "cobalt"` straight after "blackboard" in the array.

Cobalt is now available as "Color Theme".

**Comment by mattpass** [comment]
@moudsen Cobalt shows and works fine for me from the Settings > Style modal? Are you on ICEcoder v8.0?

The lines in editor.php (https://github.com/icecoder/ICEcoder/blob/master/editor.php#L42-L51) actually just set the `$activeLineBG` color, which indicates your current line. Cobalt is a color theme and works best with a black background for current line, so falls into line 50.

All seems to work well to me?

**Comment by moudsen** [comment]
Yes, I am on v8. Weird. Let me check again ... I may have overlooked somehow. ;-)

**Comment by mattpass** [comment]
No problems. 😀 Think it's all working tho, so will close, pls reopen if you get the issue again.
