### ISSUE TITLE
Tooltip (Code Assist?) taking over entire editor screen

### ISSUE THREAD

**Issue by raymondsalas** [icecoder/ICEcoder#968]
There are instances where there are tooltips taking over my code editor screen. See screenshot below. Sometimes, it completely covers the editor screen that I cannot hover to anything else in the screen to remove the tooltip. Not sure if this is code assist related since I disabled the feature and it is still persisting.

In the screenshot, I have sweetalert2 (sweetalert2.github.io) loaded in my root directory. Which are the codes being displayed in the screenshot. This occurs when I am editing a non-sweetalert JS file and hover to the "document" word of "document.getElementById(elem)"

I was only able to disable the tooltip from appearing by adding:
get('tooltip').style.display = "hidden";

under the if statement (icecoder.js > functionArgsTooltip):
if (1 === numResults && -1 === [null, "def"].indexOf(cM.getTokenTypeAt(coordsChar))) 

![image](https://user-images.githubusercontent.com/77710127/114327497-e6262e80-9b6b-11eb-911c-a34ee5298b16.png)

**Comment by mattpass** [comment]
Looks like I need to handle excess tooltip data better. Should be an easy fix, will sort that.

**Comment by raymondsalas** [comment]
It seems that terminal results may also need tweaking or word-wrapping if the line result is greater than code editor size.

![image](https://user-images.githubusercontent.com/77710127/114354181-741c0c80-9ba0-11eb-8fc7-dae9c5a6ebbf.png)

If I use, shift+mouse wheel down, other text are exposed. But the black background is cut-off, making other text harder to read:

![image](https://user-images.githubusercontent.com/77710127/114354399-c5c49700-9ba0-11eb-9256-c3a2596ffd1f.png)

**Comment by mattpass** [comment]
OK, both fixed handled - CSS in terminal needed to wrap and break as you'd expect and tooltip now limited to 200 char max re functions: https://github.com/icecoder/ICEcoder/commit/78e417add4ce575f3ff7cf5d5e6c3377b2f8a205

Thanks for reporting both 👍🏼
