### ISSUE TITLE
Suggestion: setting to trigger a webpage/script after saving

### ISSUE THREAD

**Issue by raymondsalas** [icecoder/ICEcoder#970]
This might be useful for those who want to perform additional server-side tasks after saving. Use cases:
1. Database backup after saving (or other types of backups)
2. Transfer of files to another server
3. Encryption/Obfuscation after saving
4. Simply informing another server that changes were made

Curl or file_get_contents command can be placed within "Saving Files" block of file-control.php?

**Comment by mattpass** [comment]
Well, there's actually a file where you can put your own code. See this section, it's where you can put extra code you'd like to run on save:https://github.com/icecoder/ICEcoder/blob/master/classes/_ExtraProcesses.php#L69-L78May be worth exposing this via a new `Settings` > `Processes` section however where you can set your own code easily there?
-------- Original message --------From: raymondsalas ***@***.***> Date: 4/12/21  04:28  (GMT+00:00) To: icecoder/ICEcoder ***@***.***> Cc: Subscribed ***@***.***> Subject: [icecoder/ICEcoder] Suggestion: setting to trigger a webpage/script
  after saving (#970) 
This might be useful for those who want to perform additional server-side tasks after saving. Use cases:

Database backup after saving (or other types of backups)
Transfer of files to another server
Encryption/Obfuscation after saving
Simply informing another server that changes were made

Curl or file_get_contents command can be placed within "Saving Files" block of file-control.php?

**Comment by raymondsalas** [comment]
This is great! I actually missed the _ExtraProcesses.php file and just edited the file-control.php file (which also worked for me). Yeah, exposing this in settings might be helpful for others.

**Comment by mattpass** [comment]
Yep, editing file-control.php works just as well (we just call the relevant class method (from _ExtraProcesses.php), in relevant places there anyway).

I need to document this better, and expose via Settings UI  to make it easy for everyone. 👍🏼

**Comment by hungryfrank2** [comment]
what is the code for changing directory
I want to pass the directory name to ICEcoder and then directory become the starting point

**Comment by mattpass** [comment]
You don't need to do this via code but can via the Settings > General (tab) set a root dir.
