### ISSUE TITLE
Adding a header 

### ISSUE THREAD

**Issue by hungryfrank2** [icecoder/ICEcoder#975]
I have managed to change the css file correctly and now I have a lite themed ICEcoder
I wantend to add a header section and have come to a problem
both file and editor sections become too long
I need to reduce the height of both sections

**Comment by hungryfrank2** [comment]
by the way I installed on native Apache on Mac with m1 processor and it works

**Comment by mattpass** [comment]
Sounds like you would want to adjust these lines:

https://github.com/icecoder/ICEcoder/blob/master/assets/js/icecoder.js#L202
and
https://github.com/icecoder/ICEcoder/blob/master/assets/js/icecoder.js#L222
