### ISSUE TITLE
Upload not working with docker image

### ISSUE THREAD

**Issue by Drgzidjiboy4ik** [icecoder/ICEcoder#978]
Hello, I have created docker image using manual and started icecoder container.

When I try to upload file from host I have permanently turning white bar with title "working". I just try to upload simple file and nothing happens.

**Comment by mattpass** [comment]
Hey @Drgzidjiboy4ik - sorry for the delayed reply. I've just freshly set up the Docker version of ICEcoder and an upload of a simple text file worked just fine. Also tried an image as well to test binary files and no problems either.

There's no reason it shouldn't work, but you clearly found an issue. Could you try again with your browsers dev tools open and if the same issue occurs, let me know of any JS errors shown in the dev tools Console tab? Having trouble reproducing the problem.

**Comment by mattpass** [comment]
Will close this issue, please reopen if you have issue still & error info I can look into.
