### ISSUE TITLE
Frozen: "Working"

### ISSUE THREAD

**Issue by philandy** [icecoder/ICEcoder#979]
Got it to start after a XAMPP install, and then it sort of hung on the "working" loader.
![icecoder1](https://user-images.githubusercontent.com/5067296/120911293-43160080-c654-11eb-986f-d8c2bb3cc18b.png)

**Comment by mattpass** [comment]
@philandy Can you open dev tools on the Console tab - there will be a JS error that'll help bugfix this

**Comment by philandy** [comment]
> @philandy Can you open dev tools on the Console tab - there will be a JS error that'll help bugfix this

@mattpass:
* icecoder.js:934 Uncaught SyntaxError: Unexpected token '?'
* index.php:362 Uncaught ReferenceError: ICEcoder is not defined at index.php:362
* get-branch.php?location=|&csrf=d86d35d7ff47bbb1aeb609f76f166189:30 Uncaught TypeError: Cannot read property 'filesFrame' of undefined at get-branch.php?location=|&csrf=d86d35d7ff47bbb1aeb609f76f166189:30
* editor.php:229 Uncaught TypeError: Cannot set property 'switchMode' of undefined at editor.php:229
* index.php:74 Uncaught ReferenceError: ICEcoder is not defined at onload (index.php:74)
* index.php:74 Uncaught ReferenceError: ICEcoder is not defined at HTMLBodyElement.onkeydown (index.php:74)
* index.php:74 Uncaught ReferenceError: get is not defined at HTMLBodyElement.onkeyup (index.php:74)
* index.php:74 Uncaught ReferenceError: ICEcoder is not defined at onresize (index.php:74)
* index.php:74 Uncaught ReferenceError: ICEcoder is not defined at onblur (index.php:74)

I hope it's me! XD

**Comment by mattpass** [comment]
@philandy it looks like your browser is having trouble with JavaScripts `??` (Null Coalescing), which was part of JS since about Feb 2020 I think. Upgading your browser will likely fix the issue.

**Comment by mattpass** [comment]
Will close this issue as I believe updating your browser will resolve this.
