### ISSUE TITLE
can't upload file

### ISSUE THREAD

**Issue by ngrcld** [icecoder/ICEcoder#984]
Can't upload file

PHP error from ICEcoders data/logs/error/error.log file at the time of the bug:

```
[17-Jul-2021 14:30:59 Europe/Berlin] PHP Fatal error:  Uncaught Error: Attempt to assign property "name" on null in /var/www/html/ICEcoder/classes/File.php:585
Stack trace:
#0 /var/www/html/ICEcoder/lib/file-control.php(283): ICEcoder\File->getUploadedDetails()
#1 {main}
  thrown in /var/www/html/ICEcoder/classes/File.php on line 585
```

**To Reproduce**
1. Right click on ROOT
2. Upload File(s)
3. Choose a file
4. The browser shows "working..." and the error is printed in data/logs/error/error.log

**Browser & Server (please complete the following information):**
 - Browser: Firefox 90 and Chrome 91
 - Server:
 Apache/2.4.48 (Ubuntu)
Root: /var/www/html
ICEcoder root: [Default]
PHP version: 8.0.8
ICEcoder version: 8.0 FROM MASTER BRANCH
codemirror version: 5.20.3 

**Additional context**
I have loginRequired disabled in ICEcoder/data/config-global.php

**Comment by mattpass** [comment]
Thanks for reporting this, I've fixed 2 issues related to this in commit https://github.com/icecoder/ICEcoder/commit/623ee10a8163b65484d132bc03c73441222e6cc6

Should now be working fine.
